### ISSUE TITLE
GPS position is cleared in display when telemetry is lost

### ISSUE THREAD

**Issue by KenLagoni** [yaapu/FrskyTelemetryScript#10]
First of all – great script! I really appreciate you taking the time.

I noticed that when the data link is lost, the GPS position (showed under 3D fix / hd) is cleared, but all the other data are still there. I think it should keep the last known position visible in the event of a crash.

**Comment by yaapu** [comment]
Makes a lot of sense, I'll  take a look at it, thanks

**Comment by yaapu** [comment]
Did you check if you had also lost GPS info from sensor data by displaying GPS cords on a custom telemetry page?

**Comment by KenLagoni** [comment]
I had a look at the code yesterday, and noticed something odd.
In the function “processTelemetry()” you extract all the telemetry data except for GPS lat/long (ID 0x0800). This information is first fetched in the “drawGPSStatus()” using the getValue(“GPS”) thus requiring the transmitter to have discovered the GPS sensor prior for it to Work, correct?
Now when I simulate GPS data and stop the data stream, the GPS sensor holds the last given value, thus the script works (I tested this in a separate script). 
I will test this again on my transmitter(and update to the latest openTX), perhaps the error is not with the script but with the version of openTX I’m running. :-(

**Comment by yaapu** [comment]
Hi, correct that's the way it works, GPS coords are transmitted as FRSKY standard sensors and not as passthrough encoded data, I simply "hide" gps coords when I loose a good lock, look here https://github.com/yaapu/FrskyTelemetryScript/blob/master/HORUS/SOURCES/yaapu0.lua#L2246

I should probably simply show the coords irregardless of GPS lock status

**Comment by yaapu** [comment]
Hi,
that's not the relevant code, I hide all gps info when the lock degrades, the code you pointed at would work even in case of a lost GPS for the OpenTX GPS sensor is still readable when the gps is lost.
I need to track that I had a good GPS at least once and only in this case show the coordinates along with the " NO GPS" alert

this is the correct line in the code

https://github.com/yaapu/FrskyTelemetryScript/blob/master/HORUS/SOURCES/yaapu0.lua#L2255

I'll include the fix in the next commit, didn't make it in the last one :-)

**Comment by KenLagoni** [comment]
Ahh okay my bad :-)

**Comment by yaapu** [comment]
well actually it's of great help having your own code independently reviewed, so thank you!

**Comment by yaapu** [comment]
Fixed in latest beta
