### ISSUE TITLE
No telemetry data on yappu script

### ISSUE THREAD

**Issue by Ansarida** [yaapu/FrskyTelemetryScript#100]
Hi

I am using tbs nano rx and tbs crossfire lite using X9D+ radio

Using mavlink rx tx 

i check my telemetry data i get 17 sensor, try to used the wifi connection to PC mission planer all ok
but the yappu script still not detect telemetery data

can anybody help on this matter

**Comment by yaapu** [comment]
you need to use CRSF protocol
