### ISSUE TITLE
Compatibility w/ OpenTX 2.3.11

### ISSUE THREAD

**Issue by Arktix13** [yaapu/FrskyTelemetryScript#102]
Just wondering if 1.8.0 is compatible with OpenTX 2.3.11. I'm trying to install the telemetry script on a Taranis X9D+ SE 2019 running OpenTX 2.3.11 and it doesn't seem like the script is working. I'm unable to get the telemetry screen/display to show up.

**Comment by yaapu** [comment]
Should run just fine, at least it does on my X9D 2019

**Comment by Arktix13** [comment]
I got it working with 2.3.11. I think I must have just had something messed up with my default OpenTX SD card contents. Thanks, the script is great!
