### ISSUE TITLE
Script Error Message 1.9.1 beta2

### ISSUE THREAD

**Issue by PhilColbert** [yaapu/FrskyTelemetryScript#105]
This error appears now and then, apart from that its good.

http://www.airwhere.co.uk/yappu/serror.jpg

**Comment by yaapu** [comment]
hi thnaks, any more infos on how to reproduce this error? What's your exact setup?

**Comment by PhilColbert** [comment]
It happens on boot randomly.

Taranis X9D with R9M , R9MM.

Its quite infrequent so probably close this, some unintialised variables perhaps...

**Comment by yaapu** [comment]
Hi, I've been able to reproduce it, it is a memory issue, CRSF support consumed all memory left :-(
I'm working an slim version of my script for the X9D, all features are there but the graphics is a bit lighter, I'll ask you to test it
