### ISSUE TITLE
Ground speed does not appear

### ISSUE THREAD

**Issue by PhilColbert** [yaapu/FrskyTelemetryScript#106]
Ground speed is correct on the OSD.

Stays at 0.0 on telemetry

Any ideas?

1.9.1
Radio : Taranis
R9mm - smartport
Omnibus FC

All other fields work great

Thanks

**Comment by yaapu** [comment]
check your ARSP_* settings, if you have an airspeed sensor defined but it's actually non present or unhealthy the frsky telemetry library would try to use it anyway

**Comment by PhilColbert** [comment]
Thats the one!

Thank you.
