### ISSUE TITLE
No vocal battery warning on radiomaster tx16s after a battery change

### ISSUE THREAD

**Issue by Harald69** [yaapu/FrskyTelemetryScript#107]
Hello.

using beta 1.9.3 beta
After a battery change there is no vocal message of battery level (90%, 80%,...) more. Even if I use reset telemetry  before. I need to reinitialize the telemetry by switching off the TX or changing to system menu  and back.

Thanks for your great work

BR

Harald

**Comment by yaapu** [comment]
Hi, you need to do a "reset flight", reset telemetry does not reset timers which I need to trigger a full flight reset
