### ISSUE TITLE
Show the sonar(rangefinder) value for boat

### ISSUE THREAD

**Issue by AlksSAV** [yaapu/FrskyTelemetryScript#110]

**Comment by AlksSAV** [comment]
Is it possible to add a display of values from sonar or plot a graph?
 I'm using sonar readings ( https://ardupilot.org/rover/docs/common-kogger-sonar.html?highlight=kogger) in the Mission Plan. 
My equipment: Pixhawk 2.4, Radiomaster T16S,  Frsky X4R, Kogger sonar. Ardupilot Rover 4.0

**Comment by yaapu** [comment]
Hi, the frsky library already supports sending rangefinder data pointing down i.e. RNGFND1_ORIENT = 25, so by enabling rangefidner support in my script you should get the readings.
Plotting it may require a custom panel, I've done some testing by plotting altitude on a rolling graph of 20 samples, it works but to embed it in the widget the number of samples has to be kept low, what are your requirements?

**Comment by yaapu** [comment]
this is what I can do now, this are 50 samples, not sure if it will work on a real radio
![image](https://user-images.githubusercontent.com/30294218/119951756-9a550a80-bf9c-11eb-8a5e-bfd73ce53684.png)

**Comment by AlksSAV** [comment]
> Hi, the frsky library already supports sending rangefinder data pointing down i.e. RNGFND1_ORIENT = 25, so by enabling rangefidner support in my script (use the config menu) you should get the readings.
> Plotting it may require a custom panel, I've done some testing by plotting altitude on a rolling graph of 20 samples, it works but to embed it in the widget the number of samples has to be kept low, what are your requirements?

Thank you for your work. What do you mean by the configuration menu? As I understand it, first you need the sensor to be in the list, but I do not have it( it is not found in the search). Attached is a photo with a list of sensors. To add it manually, you need as I understand the ID number, but I do not know it for RangeFinder. At the same time, the sonar telemetry data is transmitted to the MP.

**Comment by AlksSAV** [comment]
![IMG_2395 (Medium)](https://user-images.githubusercontent.com/43313549/120277070-398b4200-c2bc-11eb-8da5-1ed02d5bc239.jpg)
My list sensors

**Comment by AlksSAV** [comment]
> this is what I can do now, this are 50 samples, not sure if it will work on a real radio
> ![image](https://user-images.githubusercontent.com/30294218/119951756-9a550a80-bf9c-11eb-8a5e-bfd73ce53684.png)

It looks great, it's more than enough for me.

**Comment by yaapu** [comment]
Hi try this version please, in the config menu there's an option to select the plot sources,
![image](https://user-images.githubusercontent.com/30294218/122596420-202f1780-d06a-11eb-8d41-94cdf6c3ddad.png)

it will enable plotting those values in a dedicated screen

![image](https://user-images.githubusercontent.com/30294218/122596834-bfeca580-d06a-11eb-82de-49143da5f52c.png)

As a last step assign page 6 to a widget screen the same way as 2 is used for message history, see [here](https://github.com/yaapu/FrskyTelemetryScript/wiki/How-to-run-the-Yaapu-script-on-X10-and-X12-as-a-Widget) for more info.

[SD.ZIP](https://github.com/yaapu/FrskyTelemetryScript/files/6678469/SD.ZIP)

**Comment by AlksSAV** [comment]
> Hi try this version please, in the config menu there's an option to select the plot sources,
> ![image](https://user-images.githubusercontent.com/30294218/122596420-202f1780-d06a-11eb-8d41-94cdf6c3ddad.png)
> 
> it will enable plotting those values in a dedicated screen
> 
> ![image](https://user-images.githubusercontent.com/30294218/122596834-bfeca580-d06a-11eb-82de-49143da5f52c.png)
> 
> As a last step assign page 6 to a widget screen the same way as 2 is used for message history, see [here](https://github.com/yaapu/FrskyTelemetryScript/wiki/How-to-run-the-Yaapu-script-on-X10-and-X12-as-a-Widget) for more info.
> 
> [SD.ZIP](https://github.com/yaapu/FrskyTelemetryScript/files/6678469/SD.ZIP)


I installed the script version for sending, almost everything was successful. The results are shown in the photo below. 
The test was carried out by immersing and removing the boat from the small barrel. 
Scaling does not work in the graph( that is, the value is not clear, and the instantaneous value is not output( the RSSI value was output, for example).

![IMG_2665 (Large)](https://user-images.githubusercontent.com/43313549/123300525-54e81680-d523-11eb-843b-87d4ffba9425.jpg)

![IMG_2664 (Large)](https://user-images.githubusercontent.com/43313549/123300518-53b6e980-d523-11eb-836d-be4e7b55ea88.jpg)

**Comment by yaapu** [comment]
mhmm, I sample the value every 1 sec, I will check but I had the rangefinder working, thanks for testing

**Comment by AlksSAV** [comment]
Below is a short video with testing. In this video, I immerse and remove the sonar from a container of water. If possible, please add the ability to display only one chart( only for example Sonar, without Home distance or other items).

https://user-images.githubusercontent.com/43313549/123504091-e2308580-d65f-11eb-8134-2818cef6278a.mp4

**Comment by yaapu** [comment]
Hi, can you try this version
https://github.com/yaapu/FrskyTelemetryScript/archive/refs/heads/dev.zip

I split rangefinder which uses meters from sonar which uses centimeters, they can be selected individually.
Let me know if this fixes the scale issue

**Comment by AlksSAV** [comment]
> Hi, can you try this version
> 
> https://github.com/yaapu/FrskyTelemetryScript/archive/refs/heads/dev.zip
> 
> 
> 
> I split rangefinder which uses meters from sonar which uses centimeters, they can be selected individually.
> 
> Let me know if this fixes the scale issue

I tried this build, the result is in the photo. The value is not displayed, and at what scale the values are.![image](https://user-images.githubusercontent.com/43313549/129435498-0300d951-e947-4bd4-900a-c3a954858dd4.jpeg)

**Comment by yaapu** [comment]
version 1.9.5
![image](https://user-images.githubusercontent.com/30294218/135513700-61d60308-8b95-4799-9381-338fe1d56485.png)
