### ISSUE TITLE
Flight Mode voice/text incorrect

### ISSUE THREAD

**Issue by Squidyman** [yaapu/FrskyTelemetryScript#114]
Orange Cube
PX4 firmware
RFD900x link
OpenTX 2.3.11
Yaapu FrskyTelemetryScript is the only script

Issue: Displayed and spoken flight mode is incorrect
Altitude hold shows as stabilize, position shows as acro, mission shows as flip, hold shows sport, RTL shows autotune

Desired fix:
Text and voice match with flight mode

**Comment by yaapu** [comment]
Hi which version are you using, this was fixed but you need to use the dev branch
