### ISSUE TITLE
rfd 900 with  Horus X12S no telemetry data problem

### ISSUE THREAD

**Issue by benmar100** [yaapu/FrskyTelemetryScript#115]
i use rfd900 rx8 
Hi i have the  1.8.1 ver of yaapu
i cant get telemetry now 
it worked for a few months and today it suddenly stopped working 
thanks 
B
![60c7422c-adfd-4cf5-8f83-1f5a8e30d46f](https://user-images.githubusercontent.com/85514654/121067544-da559200-c7d3-11eb-8bea-7a695db4c4f3.jpg)
en

**Comment by yaapu** [comment]
Hi, there's no much I can do, RFD uses a custom version of the MavlinkToPassthrough project, my script/widget is just a passive consumer of that data, most likely an update of your RFD system broke it :-(
