### ISSUE TITLE
Syntax error when using Dynamic or 50Hz RF Profile

### ISSUE THREAD

**Issue by rimb05** [yaapu/FrskyTelemetryScript#118]
On my X7 using the latest script version (1.94 beta 1) and OpenTX 2.3.12 I get a Syntax Error (with no additional debug info) when trying to start the script.  The crash occurs as soon as the script starts receiving telemetry.  There's a couple of error beeps, then the crash.  I'm using a Crossfire Micro TX and Nano RX.  The problem only happens if I choose 50Hz or Dynamic in the receiver RF profile.  150Hz doesn't cause the error, and the script seems to work fine with this RF profile.  Hope this helps.

**Comment by yaapu** [comment]
hi please see https://github.com/yaapu/FrskyTelemetryScript/issues/116
