### ISSUE TITLE
Custom GMapCatherTools no longer downloading

### ISSUE THREAD

**Issue by ramiss** [yaapu/FrskyTelemetryScript#119]
Seems like the custom GMapCatcherTools is no longer connecting to any map server.  Any chance of an update or should we look at something like iFranView for resizing?

Thanks

**Comment by yaapu** [comment]
which version are you using?

**Comment by yaapu** [comment]
did you try this one?
https://github.com/yaapu/GMapCatcher/releases/tag/yaapu-0.8.2.1
