### ISSUE TITLE
Truncated messages at Taranis X9 Lite screen

### ISSUE THREAD

**Issue by RMFPV** [yaapu/FrskyTelemetryScript#121]
System messages from ardupilot at the second screen are truncated because they are longer than the screen.
Is it possible to move cropped part to the next line?

Thank you.

**Comment by yaapu** [comment]
hi, check latest dev version (dev branch)

**Comment by RMFPV** [comment]
Thanks a lot! Looks good!

Just noticed that sometimes the last string gets replaced with the following one.
![2](https://user-images.githubusercontent.com/6281367/196814648-5adb3714-eb2c-4af3-9c77-cb9558c7726f.jpg)

And here is how it looked before replacement:
![1](https://user-images.githubusercontent.com/6281367/196814747-e97559ac-6589-4ad3-b813-5944d7026908.jpg)

**Comment by yaapu** [comment]
Mhmm, I can't replicate it, that could really be a telemetry issue dropping a piece of a message, I'm pretty sure the code is ok, I did extensive simulation on this feature which is simple but tricky :-)

**Comment by RMFPV** [comment]
It happens only with exactly these two messages, all the others seems fine.
