### ISSUE TITLE
Widget language customization

### ISSUE THREAD

**Issue by bonakeem** [yaapu/FrskyTelemetryScript#123]
jumper t18
 How to change the display system language setting?

**Comment by yaapu** [comment]
which language? My scripts and widget are in english only, sounds can be personalized, labels cannot

**Comment by bonakeem** [comment]
How do I change it myself?

**Comment by bonakeem** [comment]
Utilize Open TX ..

**Comment by yaapu** [comment]
search the labels you want to change in /HORUS/SRC/WIDGET/Yaapu/main.lua and /HORUS/SRC/SCRIPTS/YAAPU/lib/*.lua
