### ISSUE TITLE
Add total batt capacity readout from INAV FC directly

### ISSUE THREAD

**Issue by jaroszmm** [yaapu/FrskyTelemetryScript#126]
I have been using the tlemetry widget for INAV and Ardu version as well and I noticed something interesting.
In Inav version the widget has option to input battery capacity so it calculates the remaining percentage based on what is set in the script.
In ardu it reads the battery capacity directly from fc.
Would it be possible for Inav version to read battery capacity from fc as well? Or am I missing something? I use Crossfire system.

**Comment by yaapu** [comment]
My widget only works with ardupilot and there already is the option to set battery capacity from the config menu or to download info from FC
