### ISSUE TITLE
Sonar plotter

### ISSUE THREAD

**Issue by AlksSAV** [yaapu/FrskyTelemetryScript#131]
Tried out the latest version everything works fine. (1.9.5) Thank you very much!
#110  
If possible, add the function of shading the graph that is below the line, for a more realistic bottom.
Below are photos of examples.
![1](https://user-images.githubusercontent.com/43313549/139525226-9f7686f2-ef4e-4fef-a336-7ba42f77f8aa.jpg)
![2](https://user-images.githubusercontent.com/43313549/139525228-520d2ec8-ddc8-48e2-b2e0-0322ff42b4cb.jpg)

**Comment by yaapu** [comment]
Hi, it's possible but it will probably cause the radio to kill the script for excessive CPU usage, my script has a lot going on in the background, I will give it a try and see, can't say when though :-)

**Comment by yaapu** [comment]
...and it wouldn't allow to plot 2 graphs

**Comment by AlksSAV** [comment]
> Hi, it's possible but it will probably cause the radio to kill the script for excessive CPU usage, my script has a lot going on in the background, I will give it a try and see, can't say when though :-)

I understand you. Device stability is more important.
