### ISSUE TITLE
EDGE TX and black screen on the middle

### ISSUE THREAD

**Issue by zefasm** [yaapu/FrskyTelemetryScript#132]
First, thanks for your great job.
I made the change OTX2.3.14 to EdgeTX 2.5.0. unfortunaltly yaapu is not working as on OpenTx. The widget is displayed but no populated data and the red “No Telemetry Data” banner is all black. 
I ve discovered all my sensors.
Please could you help me.   Screenshot enclosed
![20211127_004224](https://user-images.githubusercontent.com/57415281/143661463-df340820-6595-4d46-97f3-131fd89ebe06.jpg)

**Comment by yaapu** [comment]
Hi, as stated in the docs you need version 1.9.6 donwloadable from the dev branch
