### ISSUE TITLE
Data under telemetry, but nothing visualilzed in yaapu

### ISSUE THREAD

**Issue by tkazik** [yaapu/FrskyTelemetryScript#133]
Hi!
First of all: very cool work, thx a lot!
I am trying to set up your telemetry scripts according to [this](https://youtu.be/x4ZIeLuQyXw?t=94) guide. The issue I am running into:

On the RC, I get plenty of telemetry data:
![IMG_20211128_153149](https://user-images.githubusercontent.com/15689124/143772775-07438725-40f4-44c9-bbb9-5632ae2e8042.jpg)

But nothing gets displayed in the widget:
![IMG_20211128_153203](https://user-images.githubusercontent.com/15689124/143772794-cf84d027-21f1-4641-8a77-d63246c61835.jpg)

Any hints for further troubleshooting? Thx!

My setup:

* Radiomaster TX16s with OpenTX 2.3.14
* Jumper R8
* Pixhawk 4 Mini with latest stable arducopter

**Comment by yaapu** [comment]
Hi,
you need to set SERIALn_PROTOCOL = 10 for sport or SERIALn_PROTOCOL=23 for fport, I don't have that receiver so can't help 

From the screenshot it looks like you set SERIALn_PROTOCOL = 4

The official ardupilot docs are a better source and updated often
https://ardupilot.org/copter/docs/common-connecting-sport-fport.html#common-connecting-sport-fport

**Comment by tkazik** [comment]
Thx a lot for your fast and on spot answer...solved it.
