### ISSUE TITLE
Suggest to add data transfer

### ISSUE THREAD

**Issue by Alienix33** [yaapu/FrskyTelemetryScript#134]
Hi  Alessandro,

Your nice telemetry script works very well and  I would like to suggest an improvement.

Once Yaapu FrSky telemetry script installed all data and GPS data  in particular are well decoded and displayed on screen. However same FrSky telemetry data are not readable on Radio control Transmitter (TX16S)  UART once configured as « telemetry mirror ».

May be it could be possible to implement into LUA script some code to transfer those GPS data under NMEA format to UART which then can be configured as « LUA » ( those data would to be used by antenna tracker).

**Comment by yaapu** [comment]
mainstream OpenTX does not allow access to serial ports from lua, so no way to do it
