### ISSUE TITLE
LUA MissionSelector script

### ISSUE THREAD

**Issue by AlksSAV** [yaapu/FrskyTelemetryScript#135]
Is it possible to make it so that when activating this [script ](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scripting/applets/MissionSelector.lua)(MissionSelector.lua), you can choose which mission will be activated?

Or even a menu for selecting saved (on the SD card in Pixhawk) missions.

**Comment by yaapu** [comment]
I like the idea, not that easy to do but worth a try

**Comment by HaBaEJ20** [comment]
That would be a great enhancement!

**Comment by AlksSAV** [comment]
> That would be a great enhancement!

I'm trying to make a LUA script for a similar function (the switch selection was previously saved on the sd card of the mission)
