### ISSUE TITLE
RPM1 + RPM2 BlHeli_32

### ISSUE THREAD

**Issue by AlksSAV** [yaapu/FrskyTelemetryScript#138]
I have 2 motors connected to BLHeli_32, in MP I get RPM, AMP, Temp(ESS 5 & ECC 6). 
In Radiomaster TX16S, I have enabled receiving RPM1 + RPM2, but I am not receiving data.

BlHeli_32 DYS Aria 35A
Dshot 600 protocol
Radiomaster TX16S

**Comment by yaapu** [comment]
Hi you need to enable the correct RPM driver in ardupilot
 
// @Param: ESC_MASK
// @DisplayName: Bitmask of ESC telemetry channels to average
// @Description: Mask of channels which support ESC rpm telemetry. RPM telemetry of the selected channels will be averaged
// @Bitmask: 0:Channel1,1:Channel2,2:Channel3,3:Channel4,4:Channel5,5:Channel6,6:Channel7,7:Channel8,8:Channel9,9:Channel10,10:Channel11,11:Channel12,12:Channel13,13:Channel14,14:Channel15,15:Channel16
 
assuming your blheli motors are on channel 1,2,3,4 (like in a quad setup) you need to set the following bitmask

RPM1_ESC_MASK = 2^0 + 2^1 +2^2 + 2^3 = 1 +2 +4 +8 = 15

this will feed the average rpm of the 4 motors to sensor RPM1
If you want you can setup also RPM2 to monitor a different set of motors
