### ISSUE TITLE
What is "DGP"?

### ISSUE THREAD

**Issue by ardugitter** [yaapu/FrskyTelemetryScript#140]
Hi, I'm sorry if this was the wrong place to ask this question but what does "DGP" mean? Thanks.

**Comment by yaapu** [comment]
more context?

**Comment by ardugitter** [comment]
On the main "HUD" telemetry screen.

I think it means the number of satellites but I haven't been able to find this acronym on the internet.

**Comment by yaapu** [comment]
DGP = Differential GPS and uses satellite based augmentation (SBAS)
