### ISSUE TITLE
X20S Ethos Version Goes into Emergency mode

### ISSUE THREAD

**Issue by ninodesposati** [yaapu/FrskyTelemetryScript#141]
Install widget for X20s Ethos. Added folders to SD card: ALL/SD and X20/SD. All telemetry sensors up and running GPS, Vario, FLVSS, etc.
on Yaapu widget page getting 'NO GPS" warning on the top and a "DISARMED" in the middle of the screen. The top of the screen does show GPS coordinates. After a few minutes, the Radio goes into Emergency mode and warning sounds comes on. Locking me out of the radio and losing the signal. Disarm the widget radio is OK. Need help on this. 

added the following: Folder ALL added audio:yaapu to an audio folder on radio SD card: added folder yaapu to bitmaps on SD card.

added the following: Folder X20/SD/yaapu/bitmaps to radio SD. : Added yaaputelemety to scripts folder on radio sd.

**Comment by yaapu** [comment]
Hi, thanks for your feedback!
Can you replicate this reliably at 100%? Which ethos version?

**Comment by ninodesposati** [comment]
Using Ethos 1.1.0, Using Frsky GPS and Vario.

**Comment by yaapu** [comment]
You're not using ArduPilot?

**Comment by ninodesposati** [comment]
No Sir. Is that the reason it's doing that?

**Comment by yaapu** [comment]
Not sure what's the reason but my widget only supports ArduPilot, it's a requirement, I do not consume external frsky sensor data, a flight controller running ArduPilot is required, sorry.

BUT it should not go into emergency mode. If you can replicate, can you try to leave it running with the RX turned off, it should stay with the big red warning for no telemetry data, let's see if it crashes.

**Comment by Teklock** [comment]
I noticed after you turn off the title and exit out.  If you go back in to configure the widget a few times (usually twice) it will crash and go into 'Emergency Mode'.  I can reproduce it on a X20S.

**Comment by Nerenye** [comment]
I can replicate it with x20 on Ethos 1.1.3
ardupilot 4.17 

it´s going into emergency mode if you go a few times in the config window like Teklock mentioned.
and the widget is not fullscreen. don´t know if thats correct but it has a realy big blue border arround it like 1/3 of the screen

**Comment by Nerenye** [comment]
Anything we can do or provide to help find this issue?

**Comment by yaapu** [comment]
Fixed and thanks for the support!
