### ISSUE TITLE
Add Sensor Injection to Ethos - X20

### ISSUE THREAD

**Issue by mikedkelly** [yaapu/FrskyTelemetryScript#144]
[Enhancement] Allow telemetry sources to be discoverable in Ethos so they can be used in non-Lua widgets.

**Comment by Nerenye** [comment]
i agree

**Comment by Nerenye** [comment]
or at least custom create able.

**Comment by yaapu** [comment]
right now it is not possible

https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1141

**Comment by yaapu** [comment]
fixed by latest version by using LUA Sources
