### ISSUE TITLE
Telemetry is loaded in the model setup but doesn't update and GPS stops working.

### ISSUE THREAD

**Issue by CamGenius** [yaapu/FrskyTelemetryScript#145]
I have my autopilot setup with fport protocol=23 and and am able to load the telemetry on to my TX16S with the 1.9.6 Yappu script but it doesn't show any updates to the telemetry or on the script. Also about 10 seconds after powering on the autopilot GPS sensor coordinates are lost and never recovered. Any help with this would be much appreciated
![20220314_131730](https://user-images.githubusercontent.com/17756623/158255701-4c1876e8-56a8-46c4-8e9e-0fd1bee0fd57.jpg)
![20220314_131745](https://user-images.githubusercontent.com/17756623/158255729-1b642e6d-0394-4aef-beb6-5f9ce33b302e.jpg)

**Comment by yaapu** [comment]
Hi, this has nothing to do with my script, it looks like an ardupilot telemetry issue.
Try switching serial port and double check your serial options, you do not mention your board model and how you wired it

**Comment by Avalonnw** [comment]
Which receiver are you using?

**Comment by yaapu** [comment]
I'm closing this, if you have not solved your issue please reopen it
