### ISSUE TITLE
Add support for Ethos on Horus X12S

### ISSUE THREAD

**Issue by flouwers** [yaapu/FrskyTelemetryScript#146]
Hello,
I have an Horus X12S-ISRM running ETHOS 1.1.3.
I am trying the Dev version of the script, which I think is only foreseen for the X20.
The widget starts, but the layout is incorrect; the screen of the X12S is smaller and not everything is displayed
![PXL_20220323_082218681](https://user-images.githubusercontent.com/20664958/159655986-b1cb2212-f95b-4000-bf7c-8ca41fc90234.jpg)

Also, I have the exact same issue as mentioned in #141.
The remote goes systematically into emergency when I select "Configure widget" or "Configure screen".

**Comment by yaapu** [comment]
please check out the new version
