### ISSUE TITLE
Blackscreen on Radiomaster tx16s  EDGETX 2.6

### ISSUE THREAD

**Issue by IcemanDZ** [yaapu/FrskyTelemetryScript#147]
hello guys, I find that yappu script 1.9.5 have a bug, the script have black back ground, so I can see most the data on the pannel or menu.
![2 (2)](https://user-images.githubusercontent.com/33108085/162661377-1bb3394f-599a-4f44-b8a7-83ccb953649a.jpg)
![2 (1)](https://user-images.githubusercontent.com/33108085/162661382-5e474f8b-d7eb-4d7b-b053-fdf59ff3aec5.jpg)

**Comment by taraskornuta** [comment]
Hi. Try to play with RC Themes
I chose a theme with white background and this partially fixed the problem, but nevertheless it not solve it completely

**Comment by yaapu** [comment]
Hi, wrong version check the docs for edgetx, you need 1.9.6 or later
