### ISSUE TITLE
Yaapu script FRSKY ARCHER rs ACCESS

### ISSUE THREAD

**Issue by Pimpelpimpel** [yaapu/FrskyTelemetryScript#153]
Hi, i have small problem with yaapu script and Frsky archer rs. Do you know how i can get telemetry from it? I have tried many settings Sport/Fport different serial ports. Nothing change. When i use frsky rx6r everything works well.

**Comment by Pimpelpimpel** [comment]
Hi, i find solution for this problem :) 
I need to use 5k resistor to pull down signal and change Rc option in pixhawk to 8. It is working for frsky sport (4) and frsky Sport passthrough opentx (10)

**Comment by yaapu** [comment]
So it was HW related, ok good
