### ISSUE TITLE
Add support for Ethos on Horus X10S

### ISSUE THREAD

**Issue by greggibbons** [yaapu/FrskyTelemetryScript#158]
I have your Telemetry script running on my X20 with ETHOS and love it.
But I have two nice X10's I would like to install it on, will you be porting it to the X10s?

**Comment by yaapu** [comment]
Hi, I ported the X20 script to full screen first and next is the X10 implementation

![image](https://user-images.githubusercontent.com/30294218/174168783-46d2a735-2225-4dec-b183-8be63c754d6c.png)

time on my side though is really limited lately

**Comment by yaapu** [comment]
porting done, check the repo

**Comment by greggibbons** [comment]
I imported your new port to both my X20 and my X10s, both radio Telemetry screens show about 1/4th of the full screen, in other words 1/4th of the full Yaapu Telemetry image takes up the whole radio screen, I could not find a setting to fix it, what should I do?
![DSCN2092](https://user-images.githubusercontent.com/3287158/194602581-62ceffd3-2528-4805-b2b5-3852d096f649.JPG)
![DSCN2091](https://user-images.githubusercontent.com/3287158/194602597-3cbacf8c-12d5-4c20-a529-86e647604326.JPG)

**Comment by yaapu** [comment]
wrong layout, you need to select "Full Screen", check the new wiki section https://github.com/yaapu/FrskyTelemetryScript/wiki/Installation-on-Ethos

**Comment by greggibbons** [comment]
Thank you, that worked.
