### ISSUE TITLE
Some system messages are missing

### ISSUE THREAD

**Issue by AaryanL** [yaapu/FrskyTelemetryScript#159]
Hi!
When I run autotrim function in Arducopter, Mission planner shows all process messages as in the attachment, but none of them appear in the radio messages screen, what makes very difficult to use this function.
Can they be added please?

It's Elrs 2.1
Arducopter 4.2.1
Taranis X9D Light

![Screenshot_16](https://user-images.githubusercontent.com/84386055/174157358-09416846-0b3b-4ea4-9193-cf55f5be085b.jpg)

**Comment by yaapu** [comment]
Hi there are no filters in message handling,, do you receive any messages at all?

**Comment by RM-FPV** [comment]
Yes, I receive all other messages and warnings but not these ones.
Can be some other reason?

**Comment by yaapu** [comment]
Hi again, which ELRS rates are you using?
50Hz 1:2 will hide all info messages to save bandwidth, 100Hz 1:2 will show ALL messages.
It's an ardupilot feature I added to save bandwidth on low telemetry speed setups
