### ISSUE TITLE
Saving MAVLink Message History

### ISSUE THREAD

**Issue by BFDpilot** [yaapu/FrskyTelemetryScript#16]
Is there a way to have this data saved to a txt file somewhere. Would be great for diagnosis and problem solving. 

Also it used to be (X10S) I could roll the wheel and it would change screens with the message history but with the latest this is no longer the case?

Thanks,

Jason

**Comment by yaapu** [comment]
added message history for up to 200 messages on Horus radios in 1.9.3, saving to SD has been tried but was not reliable, closing for I can't make it safe to save that many items to SD and still do not crash the script :(
