### ISSUE TITLE
Can't have connection with my ELRS 2.4 Namimno on my Horus X10 with 1.9.6 Frskytelemetriescript

### ISSUE THREAD

**Issue by captflame2121** [yaapu/FrskyTelemetryScript#163]
Hi, I'm in ELRS 3.0 on Namimno ELRS 2.4 .
My Horus X10 is in elrs 2.7.1
My FC is with Bétaflight  4.3  

For use Frsky telemetrie 1.9.6 you can use BF or you must in ardupilot ?

If you can use BF :
I have put all on my SD  .
I can start Yappu  BUT my horus can't connect on my Elrs Namimno .

1-I have create 3 files:
mrcroc.cfg
mrcroc_right_sensors.lua
mrcroc_sensors.lua

2-In Yappu congig I have put CRSF in enable

Can you help please, I 'm sorry my English is bad .   Bests regards

I have no telemetry data and no GPS .
But the position GPS  is ok and the speed ok , all are not ok.

**Comment by yaapu** [comment]
Hi, my telemetry scripts and widgets require ArduPilot, they do not work with betaflight

**Comment by captflame2121** [comment]
Hi Alessandro ,
Thanks for your answer  but I had find .  Yes with Ardupilot.


BEST REGARDS

FLORENT

yOUR WORK IS FANTASTIC , THANKS

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : Alessandro ***@***.***>
Envoyé le :mardi 16 août 2022 23:22
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [yaapu/FrskyTelemetryScript] Can't have connection with my ELRS 2.4 Namimno on my Horus X10 with 1.9.6 Frskytelemetriescript (Issue #163)


Hi, my telemetry scripts and widgets require ArduPilot, they do not work with betaflight
