### ISSUE TITLE
Yaapu telemetry "initializing/loading layout" constant error

### ISSUE THREAD

**Issue by DarioHxC** [yaapu/FrskyTelemetryScript#164]
Every time I flip the arm or mode switch, I get this error "initializing/ loading layout" as you can see in the video. Any help would be really appreciated. 

https://youtu.be/2YAY7X4GNIE

**Comment by Johnex** [comment]
I have the same on EdgeTX 2.7.1. The Lua script works fine but every time a message arrives, it resets like @DarioHxC had.

@yaapu Is this a known issue so far?

**Comment by DarioHxC** [comment]
@Johnex havent got a hold from nobody. I think is not a common error since I haven't found anything online. I even tried in the EdgeTx group on FB and nobody said anything so far...

**Comment by txmrb** [comment]
same issue for me, Edgetx 2.7.1, ExpressLRS 2.5.1 and Yaapu Version 1.9.6 (current dev version). Since I am using the dev tree for ExpressLRS support I didnt report the issue. What yaapu Versions are you running?

**Comment by Johnex** [comment]
EdgeTX v2.7.1, Crossfire v6.19, Arducopter v4.2.2, Yaapu 1.9.6 dev.

**Comment by DarioHxC** [comment]
All the latest and greatest.

**Comment by txmrb** [comment]
Do you have the same issue on the stable Yaapu Version? My R-XSR died and I have only eLRS telemetry receivers so can't downgrade to 1.9.5. If the same issue appears on 1.9.5 it would point to EdgeTX rather than Yaapu

**Comment by DarioHxC** [comment]
I have a QX7 on OpenTx running old versions (Yaapu and Otx) that works just fine with CRSF and an old RXSR. I don't know who to blame...

**Comment by txmrb** [comment]
I mean @Johnex since we both have the same EdgeTX version, same Yaapu Version and same issue. So if he can reproduce the issue on Yaapu stable we'd know its something with EdgeTX and not the script itself. Just to get some more details for the developers.

**Comment by DarioHxC** [comment]
Send it!

**Comment by txmrb** [comment]
@DarioHxC let's keep the Comments on Topic, doesn't help if the maintainers have to scroll trough a lot of offtopic talk

**Comment by DarioHxC** [comment]
You'd better delete this last comment then...

**Comment by Johnex** [comment]
I will test in a few days, but i remember that the stable version doesn't have the CRSF variable sized packets, so it won't work properly (or at all) with the 6.19 crossfire v3 protocol.

Also, there was an issue with Yaapu and EdgeTX because of a how Yaapu was using the GVars. Seems like it's the issue we are seeing, but the EdgeTX guys say it's fixed/working? 

https://github.com/EdgeTX/edgetx/issues/2021

It's hard to understand if they are labeling "working with restarts" as working?

**Comment by Johnex** [comment]
Ahh, there is a fix for the issue here:

https://www.rcgroups.com/forums/showpost.php?p=49299729&postcount=852

**Comment by DarioHxC** [comment]
@Johnex Thanks for the investigation work. Have you tried it yet? Did it work?

**Comment by DarioHxC** [comment]
@Johnex it works!

**Comment by yaapu** [comment]
solved by Horus Version 2.0.0 beta2, no more need for GVars

**Comment by DarioHxC** [comment]
Great work! Thanks for taking the time. So should I install that version?

**Comment by yaapu** [comment]
@DarioHxC give it a try, should be pretty stable, I did many hours of simulated flights

**Comment by DarioHxC** [comment]
Grazie mille, Alessandro!
