### ISSUE TITLE
Script syntax error

### ISSUE THREAD

**Issue by GitUser8675309** [yaapu/FrskyTelemetryScript#165]
I have tried everything to get telemetry working but still nothing. In a ditch effort I am writing to ask if it could be this: In my Tarranis X9D+ 2019 tx I navigate to scripts and then execute yapuu9.lua and I get a message "Script syntax error". When I go to my telemetry screen I can see the script is running but still says "no telemetry data". I have a Matek F405WSE, Ardupilot, Frsky r9m, Frsky R9 STAB OTA. I tried with and without an external inverter. Is it possible that this syntax error could be my problem?
Thank You,

**Comment by yaapu** [comment]
Please follow the docs, you have to configure a "telemetry" script
https://github.com/yaapu/FrskyTelemetryScript/wiki/Installation-on-Taranis-radios
