### ISSUE TITLE
serial_protocol wrong

### ISSUE THREAD

**Issue by NiklasVoigt** [yaapu/FrskyTelemetryScript#170]
Ardupilot 4.2.2 with Crossfire only works with SERIAL_PROTOCOL = 29 not SERIAL_PROTOCOL = 23
please change wiki

**Comment by Johnex** [comment]
I'm on v4.2.2 and have SERIAL1_PROTOCOL = 23, you must have something wrong on your end.

**Comment by yaapu** [comment]
unrelated to my script/widget, I'm closing this :-)
