### ISSUE TITLE
Edge TX 2.7.1 with widget Edget TX 1.9.6: change page of widget doesn't work

### ISSUE THREAD

**Issue by macfly1202** [yaapu/FrskyTelemetryScript#172]
Hi, Going from Horus version on OPEN TX to Edge TX. I updated the Yaapu script and it seems that page of widget can't be change anymore with switch on radio TX16s. It was working like a breeze on OpenTX. Does this feature is broken on Edget TX ?

**Comment by yaapu** [comment]
hi, could you please test version 2.0.0 https://github.com/yaapu/FrskyTelemetryScript/archive/refs/heads/dev.zip

**Comment by macfly1202** [comment]
Hi, will test this tomorrow evening and report feed back. thanks !

**Comment by macfly1202** [comment]
Hi, quick feedback. From what I tested but because it's the night/windy, I didn't gone outside to test the maps feature with GPS signal (that was working perfectly on 1.9.6). Everything seems smooth, change screen and zoom level work as expected.
FPS is 6.8 on avionics screen and ~12 FPS on mavlink log screen. Another ciffer below FPS is 779049.
Thanks again for imprvements. I will test GPS and maps this WE if weather ok.

**Comment by macfly1202** [comment]
Some screenshots 

![IMG_1903](https://user-images.githubusercontent.com/6387630/196702063-3cd21ec5-3329-44cf-953b-09d4e6ac495d.JPG)

![IMG_1904](https://user-images.githubusercontent.com/6387630/196702112-c306a55f-3246-4fba-aa4f-0debbf4ce62e.JPG)

![IMG_1906](https://user-images.githubusercontent.com/6387630/196702147-6d84b714-932f-4dd3-b0b5-a366fb68cb55.JPG)

![IMG_1907](https://user-images.githubusercontent.com/6387630/196702201-68003eaf-03e3-4b66-90b2-0c13e034dfc6.JPG)

**Comment by yaapu** [comment]
Looking good, thanks!
