### ISSUE TITLE
Always show real number of satellites

### ISSUE THREAD

**Issue by booo** [yaapu/FrskyTelemetryScript#176]
I would prefer if the script shows the real number of GPS satellites always. Right now it stops showing the real number at some point and shows `+15` or something instead. I don't see a reason why we should hide the real number of sats.

**Comment by yaapu** [comment]
Hi, not a script lmit, nothing I can do to "fix" this, the original authors of the ardupilot telemetry library assigned only 4 bits to the sat count so it's a hardcoded limit

**Comment by booo** [comment]
That is unfortunate. Anyway thanks for your feedback.
