### ISSUE TITLE
Feature Request: Talking altimeter

### ISSUE THREAD

**Issue by booo** [yaapu/FrskyTelemetryScript#180]
One key problem with the instruments on a remote is that you loose line of sight to the plane when you take a look at the instruments. This is e.g. a big problem when you are landing. Therefore it would  be nice to have e.g. the altimeter speak to you. It should read out the current altitude in predefined intervals as soon as you are below a specific altitude. I think big airplanes have a similar feature too.

**Comment by yaapu** [comment]
Hi, telemetry speak out is natively supported by OpenTX, I won't add it sorry :-)

**Comment by booo** [comment]
Reading through the documentation of OpenTX I didn't find the mentioned feature. Do you have a pointer for me by any chance? I will take a look at the remote tomorrow.

**Comment by yaapu** [comment]
it really is trivial, this simple setup is triggered by a switch
![image](https://github.com/yaapu/FrskyTelemetryScript/assets/30294218/8840e6f4-7da7-4845-b8d2-c09dfeb8a34d)

You can make the "trigger" condition (first column and switch D in my example) as complex as you wish by using "logical switches", an example would be only play value when vehicle armed
