### ISSUE TITLE
Voltage display gets stuck on one value

### ISSUE THREAD

**Issue by booo** [yaapu/FrskyTelemetryScript#182]
During extensive test flights with our system we encountered from time to time problems with the battery voltage display. The voltage got stuck at some point during the flight and never changed over the course of the flight.

QGC/GCS still display the proper value of the battery.

Observed on a taranis X9D.

**Comment by yaapu** [comment]
Hi, what's your setup? I suspect you loose the telemetry link

**Comment by booo** [comment]
We have a Taranis X9D and a r-xsr receiver. We use a recent ArduPilot version.

Totally possible that we loose telemetry link from time to time. Other telemetry data returns at some point and gets displayed properly.

We didn't have time to collect more information about the problem while doing the flights. I will take a closer look the next time we do flights.

**Comment by yaapu** [comment]
stale for too long, perhaps reopen it if required
