### ISSUE TITLE
Any reason to install a dedicated GPG sensor such as FrSky GPS v2?

### ISSUE THREAD

**Issue by vyoufinder1** [yaapu/FrskyTelemetryScript#184]
I want to log my GPS coordinates onto the SD card of my Taranis X9D+, in case I ever lose my drone.  I'm running an Orange Cube flight controller with two GPS units on it.  Do I need to also install a smart port gps sensor to log the GPS coordinates, or does Yaapu use the information from my already installed GPS's I use for regular flying?

**Comment by yaapu** [comment]
GPS is coming from the flight controller, so your Taranis will log GPS data coming from the Cube
