### ISSUE TITLE
Update GMapsCacher link in wiki

### ISSUE THREAD

**Issue by CCSnell** [yaapu/FrskyTelemetryScript#186]
[yaapu/FrskyTelemetryScript/wiki/How-to-configure-the-Mapping-Widget](https://github.com/yaapu/FrskyTelemetryScript/wiki/How-to-configure-the-Mapping-Widget) Page links to old/broken [0.8.1.0](https://github.com/yaapu/GMapCatcher/releases/download/yaapu-0.8.1.0/GMapCatcher-0.8.1.0.exe) version. Needs to be updated to new [0.8.2.1](https://github.com/yaapu/GMapCatcher/releases/download/yaapu-0.8.2.1/GMapCatcher-0.8.2.1.exe) link.

**Comment by yaapu** [comment]
thanks, fixed
