### ISSUE TITLE
Sporadic flight mode change

### ISSUE THREAD

**Issue by arlebeckwith** [yaapu/FrskyTelemetryScript#188]
The flight mode displayed on the controller randomly changes to different flight modes for a couple seconds at a time before changing back to the correct flight mode. There doesn't seem to be any pattern and the changed flight mode doesn't seem to be the actual flight mode, it is just displayed on the controller. The incorrect flight mode is also not displayed on QGroundControl.

Horus X10s
Opentx and Edgetx
TXMod V2

**Comment by yaapu** [comment]
this s a known txmod issue, I'm closing it, you should report it to RFD
