### ISSUE TITLE
TX16s BG Text Loading Issue

### ISSUE THREAD

**Issue by orikush** [yaapu/FrskyTelemetryScript#190]
For some reason I cant get the parameter name to appear near the telemetry values (Alt, Dist, Travel, Power, etc.). This results in a few numbers being shown that aren't really clear what its for. Any help would be appreciated!
Radio: Radiomaster TX16S
Firmware EdgeTX 2.5.0
![IMG_4228](https://user-images.githubusercontent.com/115113218/213859902-d3d04d2f-9154-44ac-a6b8-dd897ad28683.JPG)

**Comment by yaapu** [comment]
For edgetx support please download latest master, the version you're using is too old
