### ISSUE TITLE
Hope to use this telemetry script in EL18

### ISSUE THREAD

**Issue by lin554893462** [yaapu/FrskyTelemetryScript#191]

**Comment by yaapu** [comment]
Hi, download latest zip and let me know how it goes :-)

**Comment by lin554893462** [comment]
ERRORin create():loadscript(/WIDGETS/Yaapu/lib/Iayoutlib.lua",""bt")error:File not foun

**Comment by yaapu** [comment]
yes I know, already fixed, sorry :-(

please redownload
