### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by KarDanenko** [yaapu/FrskyTelemetryScript#192]
hello, I really like your script, tell me how can I add 2 language packs there myself

**Comment by yaapu** [comment]
which radio?

**Comment by KarDanenko** [comment]
radiomaster tx16

**Comment by yaapu** [comment]
ok, latest version (2.0.0 dev) allows to override 4 sound categories
- base sound files
- px4 sound files
- status text hash sound files
- aerobatics tricks sound files

Translate the 4 english ".psv" [template files](https://github.com/yaapu/FrskyTelemetryScript/tree/master/OPENTX_EDGETX/COLOR%20LCD/HORUS/SD/WIDGETS/yaapu/sounds) and use [TTSAutomate](https://ttsautomate.com/) to generate the new sound files

Create a new directory for each new language under /WIDGEST/yaapu/sounds, as an example for polish create /WIDGET/yaapu/sounds/pl

Add each new language as a menu option under
- /SCRIPTS/TOOLS/Yaapu Config.lua
- /WIDGETS/yaapu/menu.lua

change this line in both files

OLD: {"voice language:", "L1", 1, { "english", "italian", "french", "german" } , {"en","it","fr","de"} },
NEW: {"voice language:", "L1", 1, { "english", "italian", "french", "german", "polish" } , {"en","it","fr","de","pl"} },

**Comment by KarDanenko** [comment]
sorry ran into a problem can't install version (2.0.0 dev) was using Horus Widget version 1.9.5

**Comment by KarDanenko** [comment]
![IMG_20230201_205540](https://user-images.githubusercontent.com/124153038/216137052-31289002-fcd5-4569-87e9-73e5f7b85caa.jpg)
![Uploading IMG_20230201_205513.jpg…]()

**Comment by KarDanenko** [comment]
![Uploading IMG_20230201_205513.jpg…]()

**Comment by KarDanenko** [comment]
![photo_2023-02-01_21-15-00](https://user-images.githubusercontent.com/124153038/216141015-8c758e28-170c-487e-8e0e-aefe05aceeab.jpg)
![photo_2023-02-01_21-15-08](https://user-images.githubusercontent.com/124153038/216141022-af945d71-4f28-406d-94c4-3927e00fbc64.jpg)

**Comment by yaapu** [comment]
Are you using ArduPilot?

**Comment by KarDanenko** [comment]
yes version 4.3.1

**Comment by yaapu** [comment]
Curr, Capa and _Bat sensors where do they come from, which RC protocol and how do you wire it?

**Comment by KarDanenko** [comment]
TBS

**Comment by yaapu** [comment]
Set rc_options = current value + 256
Enable crsf support in the widget config.
You NEED widget version 2 for CRSF support.
Use a serial port that has DMA for both tx and rx
