### ISSUE TITLE
14S battery, wrong voltage per cell.

### ISSUE THREAD

**Issue by DangerD1024** [yaapu/FrskyTelemetryScript#193]
Looks like script has limit to 12S battery while i have 14S
Script shows wrong values for 14S battery (voltage per cell)

**Comment by yaapu** [comment]
Hi, which radio and which version?
Latest versions can handle 16s but it's required to declare cell count in the config menu

**Comment by DangerD1024** [comment]
128x64 Taranis
I'll redownload latest version and check again in a few hours

**Comment by DangerD1024** [comment]
same issue... latest from github has same issue...

**Comment by DangerD1024** [comment]
> you are right, I only updated the color lcd versions, damn

Let me know when you will update bw also =)

**Comment by DangerD1024** [comment]
Or let me know how can i compile lua script)

**Comment by DangerD1024** [comment]
Downloaded latest release, still not fixed

**Comment by yaapu** [comment]
fixed in latest release
