### ISSUE TITLE
Yaapu 2.0 TX16S Edgetx 2.8 need to get GPS2 data instead of GPS1

### ISSUE THREAD

**Issue by tonysmartantzoulatos** [yaapu/FrskyTelemetryScript#195]
on tx16s with edgetx 2.8 and yaapu OTX_ETX 2.0.x dev that seems to work fine with RFD Txmod i find the 3 following issues.
1. On my ardupilot firmware FW running rover i have GPS installed on GPS2 port and configured while GPS1 is completely disabled.
While everything works fine, since yaapu is looking for GPS1 data it gives the warning on no GPS, while on incoming data stream you can see GPS2 being solid 3d fix. Can i ghange the config file to request GPS2 data instead of GPS1?
2. My PM sensor is configured as Voltage only without any Amp sensing. for some reason while i get accurate V readings, instead of having 0 amps, i get a 127 reading while on MP i can see my amp reading being zero. Is there some way to fix this?
3. wrong flight mode announced! depending on FC boot i either get correct Rover modes announced or in the correct numbering the appropriate copter mode announced, as if yaapu half the boots recongines the FC as a copter instead of a boat rover.

Still trying to download maps with gcatcher from an older PC since on win10 i have an issue (which i posted the error log), since i found that downloading from MP/google maps hybrid, does not give me a map on my screen while i can see my insternal gps working with a solid 12-13sats. Is only Gmapcatcher maps possible on 2.0 widget?

**Comment by yaapu** [comment]
Hi, issues 1, 2 and 3 depend on txmod, nothing I can do about it,please get in touch with rf design.

I offer no support for gmapcacther sorry, mine is just a repack of the official distribution with built-in tile resize, please check with the original author on official site
