### ISSUE TITLE
Menu navigation buttons t12/t-lite

### ISSUE THREAD

**Issue by kasatka60** [yaapu/FrskyTelemetryScript#196]
Jumper T12/t-lite edgetx 2.8.1
[OpenTX/EdgeTX BW LCD Radios version 2.0.0 beta1](https://github.com/yaapu/FrskyTelemetryScript/releases/tag/OTX-ETX_BW-LCD_ver_2.0.0_beta1)
Menu navigation buttons messed up.

**Comment by yaapu** [comment]
Hi, can you please give more details as I don't have that radio, thx

**Comment by yaapu** [comment]
Hi please try thsi script, it's a standalone one, copy it in the /scripts/tools folder and run it from the tools menu (same place where you have Yaapu Debug) and let me know.
[Yaapu Config.zip](https://github.com/user-attachments/files/17074247/Yaapu.Config.zip)

**Comment by kasatka60** [comment]
https://youtu.be/rjJuV5RJvPc

**Comment by yaapu** [comment]
Hi, ok, added also virtual nav keys, could you try once more using the version released on github? (need to update the whole script, not just the tool)

**Comment by kasatka60** [comment]
Ok, I'll try tomorrow.

**Comment by kasatka60** [comment]
![IMG_0453](https://github.com/user-attachments/assets/afb7d755-8d5e-4628-94cd-c9259fd0b31d)

**Comment by yaapu** [comment]
auch, I recompiled everything with edgetx 2.10, you seem to have an older radio OS?

**Comment by kasatka60** [comment]
EdgeTX v2.10.4

**Comment by yaapu** [comment]
WTF, I'll recompile with OpenTX as I used to, no idea what's wrong

**Comment by kasatka60** [comment]
It works in the simulator, but there is an error on the transmitter.

**Comment by kasatka60** [comment]
It works, but doesn't respond to buttons.

**Comment by yaapu** [comment]
OK, try the version on github, I added supporto for virtual key events, but you need etx 2.10.x

**Comment by kasatka60** [comment]
Everything works perfectly
