### ISSUE TITLE
Yaapu Telemetry not working on model 1 but perfect working on model 2 with the same config settings version 2.0.0 beta3

### ISSUE THREAD

**Issue by ojoojoo** [yaapu/FrskyTelemetryScript#197]
Yaapu Telemetry not working on model 1 but perfect working on model 2 with the same config settings and the same script version 2.0.0 beta3.
Transmitter is a TX16S with EdgeTX 2.8.0.

On both models is Yaapu Maps working perfectly with full telemetry.
On Model2 it just say "No Telemetry Data" while all the telemetry data is working, the proof is that Yaapu maps is working.

Please help, I don't know where to look for any further.

Model1
[heewingt1vtol.cfg.txt](https://github.com/yaapu/FrskyTelemetryScript/files/10983869/heewingt1vtol.cfg.txt)

Model2
[arwingpro.cfg.txt](https://github.com/yaapu/FrskyTelemetryScript/files/10983870/arwingpro.cfg.txt)

**Comment by yaapu** [comment]
did you run the debnug script with both models, does it show telemetry flowing, if not it's not a widget issue but rather an ardupilot configurationissue
