### ISSUE TITLE
Syntax error: success

### ISSUE THREAD

**Issue by Xaurin** [yaapu/FrskyTelemetryScript#198]
Hi,

Using: Latest BW 128x64 release.
When trying to save settings on Radiomaster BOXER showing syntax error: modelname.cfg success.

Can't change to CRSF protocol.
LUA debug script for CRSF ver. 1.9.5 showing no data.

**Comment by aviphysics** [comment]
any news on this issue?

**Comment by aviphysics** [comment]
Figured it out. You need to copy over the common files for your setup.

**Comment by klehnst** [comment]
Can you explain in a little more detail how you solved the problem?

**Comment by aviphysics** [comment]
> Can you explain in a little more detail how you solved the problem?
> 
> I have the same problem and did not understand your solution.

In the folder structure there are folders for specific radios, and also a folder with files common to all radios. You need both folders.
