### ISSUE TITLE
Feature Request: repiting GPS lost Alert

### ISSUE THREAD

**Issue by MFlghts** [yaapu/FrskyTelemetryScript#20]
Hi yaapu! 
It's very nice to have "GPS lost" voice alarm, but is it possible to make it repetitive as per settings 
 repeat alert every ** sec?
Sometimes it's easy not to hear it from the first time in noisy environment.
Thank you!

**Comment by yaapu** [comment]
Hi,
I did several simulations, as soon as you loose gps lock you get an ekf variance and right after that you get an ekf failsafe, the ekf failsafe alert is played every 10s so no way you "miss" the gps lost, once you get a new lock the "ekf variance" alert ceases and you get a "gps 3d fix lock" announcement, so I see no point in having a gps lost repeating alert.
