### ISSUE TITLE
Micro jet engine custom ECU read on Tandem X20s Frsky yaapu telemetry #yaapu telemetry #Tandemx20s #ECU #JetEngine 

### ISSUE THREAD

**Issue by Ghazzal14482** [yaapu/FrskyTelemetryScript#206]
I have a micro jet ecu which transmits telemetry on 3.3 volts TTL (18 bytes- Throttle,  RPM, EGT, engine state). 
I have Tandem X20s EU ETHOS and TDR10 Receiver. 
I have yaapu telemetry enabled on my transmitter. How can I read my ECU data on my transmitter. 
Should I write a custom LUA script to read my ECU data?

**Comment by yaapu** [comment]
Sorry this is totally unrelated to my script, please ask for general support in the EThos thread on discord, that would be the best place to ask for help.
https://discord.gg/wGq9ZgpXku
