### ISSUE TITLE
"no telemetry data" with ELRS PX4

### ISSUE THREAD

**Issue by M0lekula** [yaapu/FrskyTelemetryScript#207]
Hello, I have a problem after moving from Ardupilot to PX4. There is a message "no telemetry data" on telemetry widgets. 
Config: Cuav v6x, ELRS(betfpv), TX16s MKII (OpenTX).
With Ardupilot everything works fine, but after I switched to PX4, the first problem was that the TX didn't see any sensors from the PX4. I rebuilt the firmware according to [this guide](https://discuss.px4.io/t/connecting-elrs-receiver-to-pixhawk-2-4-8-under-px4-pro-possible-or-not-need-guidance/31199/2), where I enabled CRSF support, and after that I get all the sensors exactly like in ardupilot, (23 sensors), RSSI, GPS, Batt, Curr, Head, etc., but the widget still continues to write "no telemetry" as if he doesn's see these sensors. Although INAV Lua Telemetry works fine and displays all the telemetry correctly. Any ideas about this? Thx.
**No telemetry**
![1_notelemetrydata](https://github.com/yaapu/FrskyTelemetryScript/assets/41687884/a85d9d7d-8248-47e1-9530-ff13f0a34c70)
**INAV Lua Telemetry works fine**
![2_INAV_LUA](https://github.com/yaapu/FrskyTelemetryScript/assets/41687884/7ad5f747-1d56-414f-85e9-783fb041e89d)
**Sensors**
![3_PX4sensors](https://github.com/yaapu/FrskyTelemetryScript/assets/41687884/fd2d9694-24bb-42b2-aeb9-6cfa8bbdbc09)
**Yaapu Config**
![4_config](https://github.com/yaapu/FrskyTelemetryScript/assets/41687884/f04f3b19-f826-4537-9a20-bc0be6f5ea24)
**CRSF Debug**
![5_CRSF_debug](https://github.com/yaapu/FrskyTelemetryScript/assets/41687884/040b456a-2099-4559-b255-2895f8ecdf8b)
**ERLS Config**
![6_BFPV_config](https://github.com/yaapu/FrskyTelemetryScript/assets/41687884/a6494bf5-5d70-438d-aa84-d6cc4f5f7896)
**QGC 1**
![7_qground1](https://github.com/yaapu/FrskyTelemetryScript/assets/41687884/99d9b707-a574-4b6c-994b-bcfacf5bcbd2)
**QGC 2**
![8_qground2](https://github.com/yaapu/FrskyTelemetryScript/assets/41687884/e2a37972-fea2-4a98-b6c8-f64951e7da59)

**Comment by yaapu** [comment]
Hi, my widget requires ArduPilot, it uses passthrough over CRSF which PX4 does not support.
https://discuss.ardupilot.org/t/passthrough-telemetry-over-crsf-crossfire/62668
