### ISSUE TITLE
can not work with FPort

### ISSUE THREAD

**Issue by scdeny** [yaapu/FrskyTelemetryScript#21]
environment:
receiver: RXSR(flashed FPort firmware)
TX: X10S
FC: Omnibus F4V3 with INav 2.1.0
this script can not work, just "No telemetry signal" on screen.

**Comment by yaapu** [comment]
Hi this script only supports ardupilot, iNav is not supported and f.port since it's not supported by ardupilot it's not supported by this script either.

cheers,
Alex
