### ISSUE TITLE
Battery capacity  stuck when i pass 32700 mah 

### ISSUE THREAD

**Issue by ors1994** [yaapu/FrskyTelemetryScript#211]
hello every one ,
i have a weird issue with the yapuu telemetry with cube orange ,
when i consume more then 32700 mah the mah count stuck on that number in the  yapuu ( on the mission planner everything is ok and i can get up to 50,000 mah ),
any way to get pass this issue? ,
thanks

**Comment by yaapu** [comment]
This is an ardupilot limit, my script can't do much about it

![image](https://github.com/yaapu/FrskyTelemetryScript/assets/30294218/60a715c0-b750-49f4-bf3a-74ed9b1439b8)

**Comment by yaapu** [comment]
battery consumption is hard coded to 15 bits
