### ISSUE TITLE
Compass Bad Health Notification

### ISSUE THREAD

**Issue by Kyle70000** [yaapu/FrskyTelemetryScript#217]
Hi!  I have one small tiny issue.  The message screen is constantly yelling at me about bad compass health even though I haven't got a compass installed nor enabled.  I've got it disabled on ardupilot, and I've disabled all three 3 compass options thru the compass calibration screen but it still yells at me.  I am not getting this message on the mission planner log either, it's just the log on the transmitter that says it to me.  I'm almost positive this is a easy fix and it really doesn't matter that much but still would be nice to clean up.

 Thank you so much for this project its legit one of the most helpful things I've ever downloaded.

**Comment by yaapu** [comment]
hi keep investigating :-)
my script does not make up any alerts, they are all coming from ardupilot, there's something that's triggering the alert
