### ISSUE TITLE
Ethos/CRSF/Ardupilot Yaapu not showing telemetry.

### ISSUE THREAD

**Issue by VinceHogg** [yaapu/FrskyTelemetryScript#218]
Hi.
I think I have exhausted all possible settings over many days. Cant get Yaapu showing data or map info.
This system works fine with Frsky RX but now changed to CRSF and get 'no telemetry' red message.
Setup
Frsky X20s
Crossfire Nano TX/RX
Matek H743 wing running Arduplane 4.4.1 (RX on serial7 but also tried serial3)

Get a long list of discovered sensors but some (mostly RSSI type) showing as red dashes. Sometimes 'sensor lost' message.
Have tried different UART and BRD_ALT setting both 1 and 0.
CRSF support enabled in widget.

**Comment by martan223** [comment]
hi, what version of yaapu script do you use? i have the same problem with frsky X10 + ethos + r9m.
