### ISSUE TITLE
NO data displayed on widget on multiple set ups?

### ISSUE THREAD

**Issue by Daily63** [yaapu/FrskyTelemetryScript#221]
HI, I wonder if anyone could help with my problem at all briefly;

I am trying but failing to get telemetry data to display on the Yaapu widget I have tried two different setups but with the same result.
Set up one, A Frsky X20s currently on ethos 1.4.11 Eu transmitter and a TDR6 receiver on HW 1.1.0 FW 1.0.9 with a invert cable from Amazon plugged into Telem 2 Pixhawk 2.4.8 with Ardupilot 4.4.0
Set up two A Frrsky X12s on 2.3.10 Open tx and a XR8 again using a different Amazon supplied invert cable plugging into same Pixhawk 2.4.8. running Ardupilot 4.4.0

The same problem is occurring on both setups leaving me to think Im doing something wrong in the Ardupilot set up. I can have the Serial_2 Protocol set to 10 and there is nothing showing on the widget display and no extra sensors discovered. Once I change to Protocol 4 Frsky smart port I can discover about 19 sensors, but swapping back and rebooting to protocol 10 these sensors are not live anymore. On port setting 4 a NO Telem' data red screen is overlaying the widget on port setting 10 the overlay disappears but no data is being shown apart from some gps numbers.
I have tried nearly all combinations of the options on port 2 along with protocol 10 but alas no passthrough data appears to be coming from the pixhawk(apart from possibly the gps but this could be from the X20?). I have also looked at the Yaapu debug screen but every line appears to have 0 data being received?
I would love to have this app working to be able to get rid of the need for a miniOSD/seperate screen etc to discover arming issues and the like, I realise that the Yaapu widget doesn’t use sensors but the passthrough data which isn’t discoverable in the normal telemetry way however Im stumped in how to check for this function any further. Can anyone suggest a fix?

**Comment by yaapu** [comment]
Hi, this looks more like a configuration issue rather than a widget issue, you might get more help by asking for help on discuss
https://discuss.ardupilot.org/t/an-open-source-frsky-telemetry-script-for-the-horus-x10-x12-and-taranis-x9d-x9e-and-qx7-radios/26443/2205

I'd run the debug script on the 12S and check if you are getting any passthrough telemetry data at all
