### ISSUE TITLE
Map files in the zip dowmload file take too long to unzip

### ISSUE THREAD

**Issue by edgeflyer30** [yaapu/FrskyTelemetryScript#224]
Why in the Ethos folder of the zip file are there thousands of small files for map tiles? These take hours to unzip or copy to the sd card. seems unnecessary to me

**Comment by yak-54** [comment]
i don't know what your issue is
but i just tested it 
it took 11 sec to down load it
and 18 to unzip it on windows pc
?

**Comment by yaapu** [comment]
> Why in the Ethos folder of the zip file are there thousands of small files for map tiles? These take hours to unzip or copy to the sd card. seems unnecessary to me

Hi, those files are examples, you don't need to copy them to the SD card, you need to download map tiles for your area
