### ISSUE TITLE
Yaapu script broken on Ethos 1.5

### ISSUE THREAD

**Issue by iamwinq** [yaapu/FrskyTelemetryScript#226]
Ethos 1.5 has changed timers that led to yaapu script not useable... will this be updated in the revision of the Yaapu for ETHOS?

![image](https://github.com/yaapu/FrskyTelemetryScript/assets/95698959/5b396b0c-1a20-4c5a-95c1-11182db18077)

**Comment by yak-54** [comment]
Ethos brakes lot Lua scripts on 1.5.0 test firmware 
 i would say it stay like that till they release 1.5.0 as its just an beta firmware they may change it again before  its released

**Comment by yaapu** [comment]
try this in the meantime
https://discuss.ardupilot.org/uploads/short-url/pueRO57725BrEAUXi8FsUa6aCrv.zip

**Comment by JoshWelsh** [comment]
> try this in the meantime https://discuss.ardupilot.org/uploads/short-url/pueRO57725BrEAUXi8FsUa6aCrv.zip

This does seem to work for me.. I installed 1.5.2 and then this patch and so far on the bench everything seems good again.  Once again sir, you are the man!

**Comment by iamwinq** [comment]
> try this in the meantime https://discuss.ardupilot.org/uploads/short-url/pueRO57725BrEAUXi8FsUa6aCrv.zip

i have tested it as well, it works perfectly! Thank you Alex :)

**Comment by yaapu** [comment]
fixed by latest version 1.1.0 on github
