### ISSUE TITLE
airspeed and groundspeed indication with ardupilot FW

### ISSUE THREAD

**Issue by kostaslbc** [yaapu/FrskyTelemetryScript#228]
Is it posssible to display both airspeed and groundspeed with arduplane? Airspeed indication only  is not safe for long range flights .
Thanks.

**Comment by rscarawa** [comment]
Is this not already done?  I thought they show both GPS speed (same as ground speed) along with airspeed on the left side of the HUD.  
![image](https://github.com/yaapu/FrskyTelemetryScript/assets/9462118/deb2ef82-7e24-41ca-ad4c-00d0f267ef27)

![image](https://github.com/yaapu/FrskyTelemetryScript/assets/9462118/5d27c2a8-3291-4cbe-a5c6-b67291287311)

I thought the green number was GPS speed while the number under it was airspeed.  Am I incorrect?  Are the HUD elements documented anywhere?

**Comment by iamwinq** [comment]
it's working on mine though

**Comment by yaapu** [comment]
https://github.com/yaapu/FrskyTelemetryScript/wiki/airspeed-vs-groundspeed
