### ISSUE TITLE
Support for Betaflight

### ISSUE THREAD

**Issue by backman8571** [yaapu/FrskyTelemetryScript#23]
I have not seen if this will work with Betaflight

Also nothing here on setting it up for the Jumper T16 radio, is it the same as the 10S ??

Could you create a video for this

Per

**Comment by yaapu** [comment]
Hi,
this is for ardupilot only, and the X10 version "should" work on T16

you can follow the developemnt [here](https://www.rcgroups.com/forums/showthread.php?3020527-An-Ardupilot-frsky-telemetry-LUA-script-for-the-Horus-X10-X12-and-Taranis-X9D-E-QX7)

as for the video, well I'm waiting for someone to create a nice one :-)

**Comment by backman8571** [comment]
Alessandro, is it possible for you to make a version for BetaFlight.

I think its more users for betaFlight then Ardupilot

And great job by the way

Regards

Per Backman

Systems Management/Network Management
Professional Services

CELL : 4698558729

Email1 : per.backman@aurea.com
Email2 : per.backman@zephyrtel.com
SKYPE: backman8571@live.com

**Comment by LTMNO** [comment]
I would beg to differ on that topic.  ;-)

**Comment by backman8571** [comment]
Here in Texas at my club and shop's over 100 and 2 using  Ardupilot
Regards

Per Backman

Systems Management/Network Management
Professional Services

CELL : 4698558729

Email1 : per.backman@aurea.com
Email2 : per.backman@zephyrtel.com
SKYPE: backman8571@live.com

**Comment by backman8571** [comment]
How much work would it be to make it compatible with BetaFlight??

Regards

Per Backman

Systems Management/Network Management
Professional Services

CELL : 4698558729

Email1 : per.backman@aurea.com
Email2 : per.backman@zephyrtel.com
SKYPE: backman8571@live.com

**Comment by backman8571** [comment]
Also i have the Tyranis 9D and 7S

Do you have a procedure of how to get the scripts running on them 2 ??

Regards

Per Backman

Systems Management/Network Management
Professional Services

CELL : 4698558729

Email1 : per.backman@aurea.com
Email2 : per.backman@zephyrtel.com
SKYPE: backman8571@live.com

**Comment by yaapu** [comment]
Hi,
sorry but I won't make a betaflight version, you might checkt the iNav lua scripts and ask over there for betaflight compatibility!

You can find docs on how to install my scripts in my [readme](https://github.com/yaapu/FrskyTelemetryScript/blob/master/README.md#installation-on-taranis)

**Comment by backman8571** [comment]
I have no clue of how to do that

Regards

Per Backman

Systems Management/Network Management
Professional Services

CELL : 4698558729

Email1 : per.backman@aurea.com
Email2 : per.backman@zephyrtel.com
SKYPE: backman8571@live.com

**Comment by yaapu** [comment]
Hi, 
go [here](https://github.com/iNavFlight/LuaTelemetry) and ask for support.
Betaflight and iNav are much more similar than betaflight and Ardupilot.

Alex.
