### ISSUE TITLE
X20S 1.5.3 EU only show the horizon, no text

### ISSUE THREAD

**Issue by bmadeira** [yaapu/FrskyTelemetryScript#230]
With 1.5.2 I was getting lot of emergency mode, I then upgrade to 1.5.3 and apply the fix from:
 https://discuss.ardupilot.org/uploads/short-url/pueRO57725BrEAUXi8FsUa6aCrv.zip
But only the hozin is working, in the debug everting is working, AP 4.4.4

**Comment by yak-54** [comment]
looks Ethos 1.5.3 breaks yaapu working on 1.5.2 just updated to 1.5.3 now its not working at all just blank screen

**Comment by yaapu** [comment]
fixed by ethos 1.5.4, but there seem to be a couple issues introduced by 1.5.4
