### ISSUE TITLE
Ethos 1.5.4 X20 pro goes into emergency mode with screen Title on

### ISSUE THREAD

**Issue by yak-54** [yaapu/FrskyTelemetryScript#231]
Ethos 1.5.4 X20 pro goes into emergency mode with screen Title on

ethos 1.5.4 when i go through my screens this happens when i get to yaapu screen with the Title on
![20240330_075135](https://github.com/yaapu/FrskyTelemetryScript/assets/9161926/b159b951-3d84-4b36-9618-48bd28dc751e)

**Comment by yak-54** [comment]
ok worked it out with 1.5.4 when you add telemetry page remember to turn off screen Titles in your lua scripts if you leave it on go to that page the radio will crash

so looks like ethos has issues with screen Titles

**Comment by iamwinq** [comment]
let me try your suggestion. I ran into the same EM problem in the field today. i was forced to fly without the yaapu... didnt have problems in flight but it was quite inconvenient without the Yaapu

**Comment by iamwinq** [comment]
it worked! thanks buddy!

**Comment by yaapu** [comment]
fixed in latest version 1.1.0 on github

**Comment by yak-54** [comment]
thanks Alex

**Comment by iamwinq** [comment]
> fixed in latest version 1.1.0 on github

thanks!!!
