### ISSUE TITLE
Problem with taranis x9d+

### ISSUE THREAD

**Issue by yfhkucing** [yaapu/FrskyTelemetryScript#236]
Hi, does anyone knows how to solve this problem? I'm setting up the latest yaapu luascript and try to enable the crsf option. Transmitter used is taranis x9d+ with edgetx 2.9.7. Thanks in advance

![IMG_20240519_151714](https://github.com/yaapu/FrskyTelemetryScript/assets/107462467/e53f7937-0945-42c9-a158-6ac249660030)

**Comment by yaapu** [comment]
Hi please update to EdgeTX 2.10.3 and use the F2 versione of the script, should work all right
