### ISSUE TITLE
Unable to enter configuration menu on Radiomaster Pocket

### ISSUE THREAD

**Issue by gwvr** [yaapu/FrskyTelemetryScript#239]
My Radiomaster Pocket is running the "RM Factory" version (`POCKET-V2.9.0-PROD-2023.7.27-C.bin`?) of EdgeTX, with ELRS. I haven't tried updating to EdgeTX 2.10 because I've seen https://github.com/yaapu/FrskyTelemetryScript/issues/235.

The Tx is receiving telemetry from Ardupilot and I have it set up to give an audible Rx battery low voltage warning.

I've just installed the Yaapu script and it displays but shows "no telemetry". I am unable to enter the Yaapu configuration menu with TELE -> RTN -> TELE. I can bring up the Yaapu debug screens.

How do I access the configuration menu?

**Comment by gwvr** [comment]
I was unaware that CRSF passthrough needed to be enabled on the flight controller for Yaapu telemetry (if this is explicit in the Yaapu docs, I didn't see it).
This [thread/post](https://discuss.ardupilot.org/t/yaapu-telemetry-on-opentx-elrs-frsky-horus-x10/77844/18) gave me the information I needed to configure arducopter and enable Yaapu telemetry. Telemetry updates were slow initially, much improved by changing the telemetry ratio.

I still can't access the configuration menu.

**Comment by yaapu** [comment]
Hi please try thsi script, it's a standalone one, copy it in the /scripts/tools folder and run it from the tools menu (same place where you have Yaapu Debug) and let me know.
[Yaapu Config.zip](https://github.com/user-attachments/files/17074222/Yaapu.Config.zip)

**Comment by gwvr** [comment]
@yaapu that works for me, many thanks!
