### ISSUE TITLE
no telemetry data LUA Script yaapu

### ISSUE THREAD

**Issue by CpeDratDoPC** [yaapu/FrskyTelemetryScript#24]
Hello,
build: BF 3:57 Kakute  F7,  Rx Frsky X4R  F.port (SBUS + Telemetry ONE WIRE), Tx HorusX12S OpenTX 2.2.3
I guess where the dog is buried, for example
Yours:                My:
VFAS  021F 0      VFAS 0210 1
Curr    020F 0        Curr  0200 1
Fuel    060F 0        [Fuel]  0600 1 
GPS is working
(https://github.com/yaapu/FrskyTelemetryScript/wiki/Telemetry-sensors-discovery) 

![20190511_233206](https://user-images.githubusercontent.com/45167156/57575205-b08bde80-7446-11e9-9ad8-acbd05370abd.jpg)
![20190511_233220](https://user-images.githubusercontent.com/45167156/57575206-b08bde80-7446-11e9-8028-bd1a4dcee928.jpg)
![20190511_233258](https://user-images.githubusercontent.com/45167156/57575207-b08bde80-7446-11e9-9fbb-824f07705cb1.jpg)
![20190511_233319](https://user-images.githubusercontent.com/45167156/57575208-b08bde80-7446-11e9-9742-629c8ddaa42a.jpg)
![20190511_233332](https://user-images.githubusercontent.com/45167156/57575209-b08bde80-7446-11e9-9f93-02cc8bcd2f8f.jpg)
![20190511_233353](https://user-images.githubusercontent.com/45167156/57575210-b1247500-7446-11e9-8cad-ad879fd6133f.jpg)

**Comment by yaapu** [comment]
Hi this script supports only [ardupilot passthrough telemetry](http://ardupilot.org/copter/docs/common-frsky-passthrough.html).
Betaflight is not supported.
This script does not use sensors to get telemetry from the flight controller but rather exposes as sensors the data received via the passthru protocol.
