### ISSUE TITLE
GPS position on FrSky TWIN X Lite S is incorrect

### ISSUE THREAD

**Issue by stefan1messmer** [yaapu/FrskyTelemetryScript#241]
The Yaapu telemetry script displays wrong GPS position on FrSky TWIN X Lite S. The displayed latitude and the longitude values are identical and depend from the actual position. The GPS position in the telemetry page, however, is correct.
ETHOS Firmware Version 1.5.11 EU 
Bootlader Version 1.14.16
Module Version 1.0.6

Ardupilot version 4.4.x running on Holibro Pix32V5

**Comment by yak-54** [comment]
ethos 1.5.11 broke this
 they have change something in the way it handles gps
![Uploading 20240726_214734.jpg…]()

**Comment by yak-54** [comment]
![Uploading 20240726_214734.jpg…]()

**Comment by yaapu** [comment]
Hi, this is how it should have (ever) been :-)

    gpsData.lat = system.getSource({name=status.conf.gpsSource:name(),options=OPTION_LATITUDE}):value()
    gpsData.lon = system.getSource({name=status.conf.gpsSource:name(),options=OPTION_LONGITUDE}):value()

thanks for your help @stefan1messmer

**Comment by stefan1messmer** [comment]
I found the same solution last weekend, but could not evaluate it carefully up to now.

Best regards
Stefan
