### ISSUE TITLE
No telemetry data on ETHOS 1.5.11 Tandem  X20s

### ISSUE THREAD

**Issue by fdapport** [yaapu/FrskyTelemetryScript#242]
TX: Tandem X20s
SO TX: Ethos 1.5.11 FLEX
RX : R9 Slim +   868Mhz
SO Rx: 1.3.1
Controller: Matek F405 WIN
SO Controller: Arduplane V.4.0.8

On Open TX all work, include receiving telemetry data. I have installed Yapuu LUA end I have the following Error:
ONLY GPS coordinate sensors is discovered:  See below 

![20240811_181831](https://github.com/user-attachments/assets/02c1aca2-418d-47b9-a4f6-49b21ca78d2e)

If I run the LUA Telemetry Debug all the sensors are received:

![20240811_181858](https://github.com/user-attachments/assets/e5daa517-02c5-4b54-a01c-1846aec2a9d3)

If I set LUA Sensors in the model 

![20240811_182017](https://github.com/user-attachments/assets/01e2e72b-2175-432a-ae68-219864940a56)

I have the following error:

![20240811_182235](https://github.com/user-attachments/assets/498401e2-3692-4d0c-94fe-095a9aad3b60)

Please somebody could help me to removed the error. Thanks, Franco

**Comment by fdapport** [comment]
I have run again with the last Yaapu version 1.1.0, same error but in a different line number (#1689) 

![20240811_220249](https://github.com/user-attachments/assets/3f035428-5f64-470c-9abe-4adf46e4bbea)


This is the wrong line...

![LUA - Copia](https://github.com/user-attachments/assets/7473e9b9-c5a3-43d4-a681-d8f08dde1551)

**Comment by yaapu** [comment]
Hi, tested this with 1.5.14 and it seems to work, can you upgrade and recheck? perhaps it was a bug?

**Comment by fdapport** [comment]
Ok,  I will update the radio first and reload the scripts and I will let you know if it is all ok.... Thanks for the check. Ciao., Franco

**Comment by fdapport** [comment]
I have update the radio to 1.5.15 version, yaapu works!!! . Thanks, Franco
