### ISSUE TITLE
Radiomaster MT12 - enter config screen

### ISSUE THREAD

**Issue by rain-er** [yaapu/FrskyTelemetryScript#244]
Radiomaster MT12 works with "bw128x64" scripts.
MT12 has keys SYS, MDL, Page+, Page-, RTN, TELE, but no MENU-Button to access the Yappu config screen.
"RTN and TELE" key combination did not work. I use EdgeTx 2.10.3.

With this litte change the config screen can be accessed with longpress TELE key.

yaapu7.lua:
```
    -- elseif event == EVT_MENU_LONG or event == 128 then
    elseif event == EVT_TELEM_LONG or event == 128 then
```
Workaround to activate:
- install Yaapu as usual on MT12
- on MT12 SCRIPTS/TELEMETRY folder delete "yaapu7.luac"
- copy "yaapu7.lua" from the repository to MT12 and change as shown above
- start Yaapu telemetry. "yaapu7.lua" will automatically be compiled to "yaapu7.luac"

**Comment by yaapu** [comment]
Hi, I do not have the time to adapt the script to every single radio out there and I know there are many workarounds, so thanks.

Hi please try this script, it's a standalone one, copy it in the /scripts/tools folder and run it from the tools menu (same place where you have Yaapu Debug) and let me know.
[Yaapu Config.zip](https://github.com/user-attachments/files/17074236/Yaapu.Config.zip)
