### ISSUE TITLE
No telemetry data on ETHOS 1.5.15 Tandem X20pro

### ISSUE THREAD

**Issue by bad-wm** [yaapu/FrskyTelemetryScript#245]
TX: Tandem X20pro
SO TX: Ethos 1.5.15 fcc
RX : elrs 2.4
SO Rx: 3.3.0
Controller: FLRC H7D MK1 H743
SO Controller: Arduplane V.4.5.5
The ethos 1.5.15 system follows the installation method in the wiki and uses the ELRS receiver to always display 'no telemetry'. The widget can display the set feedback data such as link quality,

**Comment by bad-wm** [comment]
![af2744293677c81fc4025616a2fbcc4](https://github.com/user-attachments/assets/041b2797-8442-401c-b53c-6d22fd944cde)
![8155218f5287ce3ee5f89f8141265c5](https://github.com/user-attachments/assets/8b15c21a-4bca-41f4-bb29-8ef04e6d0fce)
![Uploading bd6d4ed10053eb616a04ffb8fd4cd79.jpg…]()

**Comment by yaapu** [comment]
Hi did you enable arduplane custom CRSF telemetry by setting RC_OPTIONS += 256?, this looks like an ardupilot configuration issue

**Comment by bad-wm** [comment]
Okay, thank you very much. I overlooked the issue with ardupilot. Also, I would like to ask if yaapu only supports ardupilot, and if it supports BF or INAV.

**Comment by yaapu** [comment]
as of now it requires Ardupilot

**Comment by bad-wm** [comment]
Okay, thank you very much for answering my question
