### ISSUE TITLE
No telemetry data x9d+

### ISSUE THREAD

**Issue by anahoua16** [yaapu/FrskyTelemetryScript#246]
Hi, I am not able to get the yaapu script working on my Taranis X9D+ (No telemetry Data).

image

After reading some posts, it seems that I have to enter the telemetry settings screen of Yaapu to set it to CRSF Telemetry, however I am not able to figure out how to enter this screen / menu in my X9D+ ?

For reference, here are my settings:

FC: OMNIBUS F4 Pro ( Rx Connected on Serial1)

EdgeTX ver: 2.10.3

ELRS:

    Radiomaster Ranger Micro Tx & RP1 Rx
    Ver: 3.4.3 ISM2G4
    Packet Rate: D250
    Telem Ratio: 1:2
    Switch Mode: Wide

Arduplane ver: 4.5.5

image
[image755×205 5.87 KB](https://discuss.ardupilot.org/uploads/default/original/3X/e/a/eaf55c7f8128b7f35881e30ee964708e8d266e58.png)

image
[image868×132 7.86 KB](https://discuss.ardupilot.org/uploads/default/original/3X/b/f/bf1ea481f15ff0174c3282e472e3cfc345db6ca4.png)

image

https://discuss.ardupilot.org/t/yaapu-taranis-x9d-how-to-telemetry-settings-screen/123132

**Comment by yaapu** [comment]
Hi long press the MENU button while the script is running
