### ISSUE TITLE
Telemetry script is freezing on TX16S running Crossfire and EdgeTX "Centurion" v2.10.4. Latest Dev version of Yaapu as of this week.

### ISSUE THREAD

**Issue by marcdornan** [yaapu/FrskyTelemetryScript#248]
I am getting a very reliable script freeze after a few minutes of flight. The radio power button also freezes although thankfully the RC channels still work. Latest release of Edge Tx Centurion. I will post on EdgeTX github as well. This is not happening when I use Yaapu with SPort telemetry with Dragonlink (Mavlink) so I think this is related to CRSF.

**Comment by marcdornan** [comment]
Update -- it seems Crossfire was giving very low telemetry rates (.3 hz) and this was causing the issue, especially after arming when there was more telemetry traffic. Once I updated and rebound I do not seem to be having the LUA script freezing.

**Comment by yaapu** [comment]
hi, try to increase the telemetry to RC ratio

**Comment by yaapu** [comment]
ok, I'm closing it
