### ISSUE TITLE
No telemetry when using MAVLink instead of CRSF (ELRS)

### ISSUE THREAD

**Issue by alexandru-g** [yaapu/FrskyTelemetryScript#249]
When switching serial protocol from CRSF to MAVLink, the telemetry script only displays "no telemetry", although the ELRS documentation specifies "Your TX converts the MAVLink telemetry into standard CRSF format which is understood by EdgeTX" ([Source](https://www.expresslrs.org/software/mavlink/)), so nothing should be different.

**Comment by yaapu** [comment]
not supported.
CRSF built from Mavlink is not Ardupilot custom CRSF frames
