### ISSUE TITLE
Wrong direction of the arrow

### ISSUE THREAD

**Issue by sergeyfatman** [yaapu/FrskyTelemetryScript#250]
Radiomaster TX16S MK2 (fw EdgeTX "Centurion" v2.10.4), FrskyTelemetryScript v2.0.0 beta3, receiver FrSky X8R
![изображение_viber_2024-09-15_00-18-54-8301](https://github.com/user-attachments/assets/a2bad461-da68-48b9-aa7f-af7b451602a9)

**Comment by yaapu** [comment]
the arrow points toward home, it means turn left to go home

**Comment by sergeyfatman** [comment]
> the arrow points toward home, it means turn left to go home

Thank you

**Comment by yaapu** [comment]
https://github.com/yaapu/FrskyTelemetryScript/wiki/Screen-layout
