### ISSUE TITLE
Flight Controller Voltage - trying to find the associated BIN log file parameter

### ISSUE THREAD

**Issue by joe-stroup** [yaapu/FrskyTelemetryScript#253]
I'm using the Horus version of Yaapu on a RadioMaster TX16S.

I'm trying to understand the reported "FC V" (I assume that means flight controller voltage).  In the following photo, this displays with a red background in the upper righthand corner.

![PXL_20240923_143609354](https://github.com/user-attachments/assets/ad5f1836-2bee-4c23-b1cb-c6bcd588abb7)

I'm trying to find the associated parameter in the BIN log files so I can diagnose this.  I checked the POWR.VCC parameter - but this shows above 5V.

![image](https://github.com/user-attachments/assets/a9b8e5e9-7d7a-4a16-930a-4a5097bcae20)

Can someone please advise me where to look for this data so I can troubleshoot it.

I'm using the default Yaapu parameters on my transmitter.  But perhaps I have to make an adjustment.

Many Thanks!

**Comment by yaapu** [comment]
Hi, that's the average cell voltage, the battery voltage is 14.9, the script is guessing you have 4s, you can override it in the yaapu config menu
