### ISSUE TITLE
Meaning of "T" and "F" symbols

### ISSUE THREAD

**Issue by joe-stroup** [yaapu/FrskyTelemetryScript#256]
I'm using the 1.9.5 Horus version on a RadioMaster TX16S and Crossfire.

I can't seem to locate information that explains what the "T" and "F" symbols that sometime appear on the screen.

Is there a place that explains these symbols?

![yaapu t and f symbols](https://github.com/user-attachments/assets/7d35a719-964c-4970-a7d0-1cc73fb7c07b)

**Comment by yaapu** [comment]
Hi, documentation is lagging behind, sorry about that.
T= terrain
F= fence

when terrain is available and healthy, altitude will be reported as HAT (height above terrain) in green whilst altitude above home in white, if terrain is not healthy T will flash and an audio warning is triggered

if a fence is active an F is displyed, if you "break" the fence a warning is issued and F will flash

**Comment by yaapu** [comment]
...and please update your widget to latest

**Comment by yaapu** [comment]
![image](https://github.com/user-attachments/assets/97dbb896-5e30-47ad-a103-2179dd317d1e)
