### ISSUE TITLE
FrSKY X9D PLUS Taranis "not enough memory"

### ISSUE THREAD

**Issue by Kadam23** [yaapu/FrskyTelemetryScript#26]
Dear,
i installed the script on my FrSKY X9D PLUS Taranis. Starting script report "not enough memory".
Regards,
Carlo

**Comment by yaapu** [comment]
Hi,
this happens when you try to compile the script on the radio.
You need to copy the binary version from https://github.com/yaapu/FrskyTelemetryScript/tree/master/TARANIS/SD 
to your radio SD card.
Then configure the script as a telemetry one. 
Make sure it's the only script running.

**Comment by yaapu** [comment]
is this solved?

**Comment by Kadam23** [comment]
Dear,
I've to try removing other plugin. I let you know.
Thx

Il gio 8 ago 2019, 10:34 Alessandro Apostoli <notifications@github.com> ha
scritto:

**Comment by StrategicVisionary** [comment]
I would confirm and reemphasize make sure the Yaapu script is the only one running. My memory error problem abated after removing the farl script on the second telemetry page.

**Comment by yaapu** [comment]
...another thing to watch for is OpenTX vs EdgeTX with the latter (version 2.8.x) leaving much less memory to LUA scripts

**Comment by srhassan71** [comment]
@Alex, does this mean EdgeTX + ELRS on Taranis X9D (ACCST) cannot run Yaapu?
I don't have any other scripts running, and when I try to enable CRSF protocol (Yes/No), it gives me an error "Not enough memory"

**Comment by ZSeymour1** [comment]
I've had this same problem. My mistake was to copy the contents of the SRC folder into the SD card's SCRIPTS/TELEMETRY folder - don't do that! Hope this helps :)

**Comment by pierpiero83** [comment]
> [@yaapu](https://github.com/yaapu) (Alex), does this mean EdgeTX + ELRS on Taranis X9D (ACCST) cannot run Yaapu? I don't have any other scripts running, and when I try to enable CRSF protocol (Yes/No), it gives me an error "Not enough memory"

I have same issue, it appears that I cannot change the Telemetry protocol to FRSF. 
Did someone solve this out on the Taranis x9D plus?
