### ISSUE TITLE
Expose Flight Mode numeric value from ArduPilot MavLink to OpenTX

### ISSUE THREAD

**Issue by JoshWelsh** [yaapu/FrskyTelemetryScript#27]
Hey there.. we have a need to do a mix in the radio that is dependent on the ArduPlane Flight Mode numeric value.  Is it possible to expose this to OpenTX from your widget as a sensor along with the others that you're exposing?

**Comment by yaapu** [comment]
Hi Josh,
sure it's an easy mod you can do yourself, what radio do you have?

**Comment by JoshWelsh** [comment]
Hey Alessandro, thanks for asking, running a Horus.

On Jun 24, 2019, at 3:38 AM, Alessandro Apostoli <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Josh,
sure it's an easy mod you can do yourself, what radio do you have?

**Comment by yaapu** [comment]
Hi,
add this line 

`setTelemetryValue(0x060F, 0, 2, telemetry.flightMode, 0 , 0 , "FMOD")`

as last instruction of this function
https://github.com/yaapu/FrskyTelemetryScript/blob/master/HORUS/SOURCES/PP/main.lua#L1173

and copy main.lua to the WIDGETS folder

cheers,

Alex.

**Comment by JoshWelsh** [comment]
Hi Alessandro,

I’ve done what you instructed here:

https://github.com/JoshWelsh/FrskyTelemetryScript/blob/1102effc825ebf4492e80fcf23b33ca55d7d8e81/HORUS/SOURCES/PP/main.lua#L1208

When I copied the file over, it reverted the widget back to 1.7.4 from 1.8rc2, whos main.lua appears to be binary?  I think I may have just messed the whole thing up though, can you advise?

**Comment by yaapu** [comment]
mhmm my fault, you have told you it was based on 1.7.x, try this patched version anc copy it to the widgets/yaapy/folder

[yaapu_widget.zip](https://github.com/yaapu/FrskyTelemetryScript/files/3325007/yaapu_widget.zip)

**Comment by JoshWelsh** [comment]
My apologies sir, I should have been more clear. Thank you for this, will try it later today and report back.

On Jun 25, 2019, at 4:34 AM, Alessandro Apostoli <notifications@github.com<mailto:notifications@github.com>> wrote:


mhmm my fault, you have told you it was based on 1.7.x, try this patched version anc copy it to the widgets/yaapy/folder

yaapu_widget.zip<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyaapu%2FFrskyTelemetryScript%2Ffiles%2F3325007%2Fyaapu_widget.zip&data=02%7C01%7Cjosh%40joshco.us%7C9e36c37d02a1467e741908d6f9611504%7C66a80cae9a51453283356eed78d28e07%7C1%7C0%7C636970592699341768&sdata=aSeU4DBNDykrulk5tDmRubzcKMT2EDCbHxFkseUHNdM%3D&reserved=0>

**Comment by yaapu** [comment]
Josh I'm closing this, if you need more help open a new issue!
