### ISSUE TITLE
Missing file on GitHub

### ISSUE THREAD

**Issue by srhassan71** [yaapu/FrskyTelemetryScript#45]
I cannot find the Yaapu file "taranis_1.8.0_rc1.zip".

**Comment by yaapu** [comment]
Hi, why do you need an RC version?

to get the latest release simply download the latest [master](https://github.com/yaapu/FrskyTelemetryScript/archive/master.zip)

**Comment by srhassan71** [comment]
Hi Alessandro,

I am following Painless360 instruction and the zip file shows RC version. Is there a new version? 
I also notice that there are three folders I need to copy on my sd card for yaapu to work. What if there are already folders with such names on my SD card with different content? Can I rename yaapu folders?

Appreciate some tips.

Thanks
Riz

**Comment by yaapu** [comment]
Hi, did you read the installation [wiki](https://github.com/yaapu/FrskyTelemetryScript/wiki/Installation-on-Taranis-radios) for taranis radios?
Folders should not be renamed, simply copy as explained in the wiki.

**Comment by srhassan71** [comment]
Thanks for the link. I guess its better to read than follow videos. I
updated my Taranis from 2.2.3 to 2.2.4, updated SD card and than uploaded
Yaapu. It worked!

Thanks again,
Riz

**Comment by yaapu** [comment]
Hi RIz, well yeah videos are fine, but if not maintained they get old very fast.
Good job, I tested the script also with OpenTX 2.3.4.

cheers,

Alex
