### ISSUE TITLE
No values in the telemetry radio screen

### ISSUE THREAD

**Issue by fdapport** [yaapu/FrskyTelemetryScript#51]
I have the following question/Issues:
Radio: Taranis X9D+ Firmware: 2.3.5  RX: R9 slim on 868Mhz

When I run the yaapu script   I see all the values send from the F405-Wing but when I go in the telemetry menu of the radio I see only the GPS Coordinate, I see the other sensors (CURR, Volt, ALt, etc) but NOT ANY values.. I am not able to set the special functionality of the vario or the voice features. Is some thinks that is possible to solve? Thanks, Franco

![20200328_105101 - Copia](https://user-images.githubusercontent.com/42831968/77821141-2c872780-70e8-11ea-9de4-c445ba69fe76.jpg)
![20200328_105115](https://user-images.githubusercontent.com/42831968/77821145-33ae3580-70e8-11ea-8c1d-e888b58e6428.jpg)

**Comment by fdapport** [comment]
I have resolved, sorry,, just search again the sensors. It is working.

**Comment by yaapu** [comment]
ok great, I'm closing this.
