### ISSUE TITLE
PITLAB OSD - Mavlink intergation with Yaapu lua scripts & Ardupilot

### ISSUE THREAD

**Issue by uros2020** [yaapu/FrskyTelemetryScript#57]
Hi Alex

so i bought PITLAB OSD Mavlink component for FPV, connected to cube through telemetry port-1 (only TX, RX, GND). On telmetry port-2 I have connected Dragonlink Rx connected with 6-pin cable (from FPVPRO).

PITLAB OSD works, but telemetry voice from Yaapu lua scripts installed on RC (jumper T16 pro with Open TX) keeps repeating all the time: armed… disarmed…armed.....etc. On the other hand on my PC the Mission planner (Ardupilot) all the time shows status: disarmed (see video in atatchment).… If I disconect Pitlab OSD (power OFF) the voice/notification on the RC (jumper t16 pro) stops. 

So i heard could be that: Pixhawk/Cube acts as a hub and transfers OSD’s heartbeat to telemetry stream but not distinguish between Cube and OSD heartbeats, and shows (speaks) status from both heartbeats messages. ...something like this maybe explaind wrong. Please see video in zip --- > i put together PC with Mission planner (right) and lua scripts on RC display (left)  ....and you can hear that lua scripts on RC keeps telling me armed>disarmed>armed...etc but on PC Mission planner keeps showing status disarmed all the time. 
Telemetry goes:  FC Pixhawk/Cube > Dragonlink Rx receiver with telemetry > Dragonlink Tx transmiter > Heltec wifi kit ESP32 (latest version of MavlinkToPassthru) > RC (open tx with installed lua scripts)

Possible to add this line:

Autopilot = MAV_AUTOPILOT::MAV_AUTOPILOT_INVALID; //  /*==8 No valid autopilot, e.g. a GCS or other MAVLink component | */

maybe would solve my issue....or pleaseeee tell me where to modify this code...please please help.

THANKS, Uros

[OSD.zip](https://github.com/yaapu/FrskyTelemetryScript/files/4673339/OSD.zip)

**Comment by yaapu** [comment]
Hi this looks like an issue on the MavToPT code not on my widget, you should open an issue there.

I found this commit https://github.com/zs6buj/MavlinkToPassthru/commit/d28a6ff459ce0f579d7854d547e869408c23fff3 look relevant
