### ISSUE TITLE
Error running Telemetry Widget on Horus X10S

### ISSUE THREAD

**Issue by Hennyvt** [yaapu/FrskyTelemetryScript#58]
I used the YAAPU script on my old version on Horus X10S and it operated fine. I now have the the Express version Horus X10S running Opentx 2.3.7 and am unable to run the script. I have tried script version 1.8.0 and 1.8.1 and neither will run. One noticeable effect is if I attemp to run the script the radio deletes the 2 scripts in the Yaapu folder in the widgets folder. Do you have any suggestions.

Thank you

**Comment by yaapu** [comment]
Mhmm can you reformat the SD card, looks like corruption

**Comment by Hennyvt** [comment]
Yes that was the it. I tried everything. Thank you its running very well now.
