### ISSUE TITLE
V1.8.0 QX7 OTX2.3.7 Config missing - when long press Menu

### ISSUE THREAD

**Issue by WillyZehnder** [yaapu/FrskyTelemetryScript#59]
When I long press Menu, there is a TOOLS list, but "Yaapu Debug" is the only tool from Yaapu. The others are Crossfire, FrSky, Graupner and Spectrum. I searched for *.lua on SD-card, but a "Yaapu Config.lua" or similar is missing.
How can I start the Configuration?

**Comment by yaapu** [comment]
Hi, on the Taranis radios like the QX7 you access the config menu by long pressing the [menu] button while on the script main page.

**Comment by WillyZehnder** [comment]
Thank you for the hint Alex!
Maybe you should insert a half-sentence in the README.
configuration menu, long press [MENU] **while on the script main page** on Taranis or long press [SYS] on Horus (refer to this guide)
