### ISSUE TITLE
Always "Stabilised Flightmode"

### ISSUE THREAD

**Issue by Seeelefant** [yaapu/FrskyTelemetryScript#6]
Hi Alex,
I am running a PixRacer/MavlinkToPassthru/QuadCopter Combination. So far almost everything works fine, however I am always getting independent from the Mode I choose.
I discussed that issue already with Eric (https://github.com/zs6buj/MavlinkToPassthru/issues/8#issuecomment-414108222),  and he proposed that you might help.
Best 
--Seeelefant
[LOG.txt](https://github.com/yaapu/FrskyTelemetryScript/files/2300270/LOG.txt)

**Comment by yaapu** [comment]
Hi what flight stack are you running, ardupilot or px4? 
From the mavlink log I see that flightmode is always 1 so it appears that mavlink is not transmitting the info, how's the cabling?

**Comment by Seeelefant** [comment]
Hi Alex,
I am running PX4. I was following Eric´s cabling instructions, so **every** other info is transmitted, **only** the Flight Mode is missing.

Eric pointed out that:

``Yes, f**light mode is derived from ap_custom_mode** on the mavlink heartbeat record, and also depends on the type of frame - ap-type. Obviously a quadcopter does not have the same flight modes as a fixed wing aircraft, an so on.

The LUA script determines the correct flight mode name and enunciation.

If there are other "sensors" on the bus, the Taranis and the LUA script need to decide which one to use for flight-mode. Alex (yaapu) can probably help with that.

Good luck
Eric´´

Best
--Seeelefant

**Comment by yaapu** [comment]
Do you have any other mean to check if flight modes are correctly sent over mavlink, like an OSD?
My script can only decode what the teensy is sending and from the log the teensy is not getting the flightmodes from the mavlink stream the way ardupilot sends them.
The frame type is correct, ap_type=2 means copter, but the flight mode is not decoded the correct way, from this https://github.com/mavlink/mavlink/issues/774 it appears that ap_custom_mode decoding is flight stack dependent, so the values received have to be decoded the PX4 way following this https://github.com/PX4/Firmware/blob/master/src/modules/commander/px4_custom_mode.h#L45

**Comment by Seeelefant** [comment]
Hi Alex,
I can see the Flightmodes in QGroundcontrol, but´s that´s not ideal....I would like to have **one** place with all the relevant infos..... Is there an option that I modify Eric´s script? What message/format do you need for the right Flight Modes?

Best
--Seeelefant

**Comment by yaapu** [comment]
Mavlink ap_custom_mode has to be decoded according to https://github.com/PX4/Firmware/blob/master/src/modules/commander/px4_custom_mode.h#L45

**Comment by yaapu** [comment]
Eric and I are working on :)

**Comment by Seeelefant** [comment]
I´m happy to hear that, it´s highly appreciated :-) .
Best
--Seeelefant

**Comment by yaapu** [comment]
Hi Seeelefant, could you post a telemetry log file .tlog of a flight or of a simple bench flight where you switch some flight modes, I need it to bench test the script against PX4 flight modes

Alex

**Comment by Seeelefant** [comment]
Hi Alex,
currently I only have this log
[LOG.txt](https://github.com/yaapu/FrskyTelemetryScript/files/2321795/LOG.txt)
, is this sufficient?
--Seeelefant

**Comment by yaapu** [comment]
Hi, do you have the telemetry log files produced by mission planner,  qgroundcontrol or tower? They are binary files with the tlog extension, they are the kind of files that you can load in GCS software to replay a flight

**Comment by Seeelefant** [comment]
Sorry,
currently not...my Quad is currently broken. May I drop you a line once it is running again ... with fresh logs?
--Seeelefant

**Comment by Seeelefant** [comment]
Hi Alex,
my Quad is working again, however currently PX4 has quite some problems with CAN buses.  Therefore I switched to ArduCopter and things are working there 🥇 .
May I ask another question:
Here https://github.com/Clooney82/MavLink_FrSkySPort/wiki/1.-Setup there is a section on "Combining Teensy with FrSky Sensors". Is this still possible with your solution, can your script grab these values?
Here https://github.com/Clooney82/MavLink_FrSkySPort/wiki/2.1.-Lipo-Singe-Cell-Monitor there are some remarks how to (mis-) use the Teensy for voltage measurement of the single cells. Could that be implemented within your environment? Which solution would you recommend?

Best
--Seelefant

**Comment by yaapu** [comment]
Hi,
Passthrough telemetry can share the s.port bus with regular frsky sensors so all frsky sensors can be used with my script, they will be discovered just fine and won't interfere.
If you use 1 or 2 FLVSS sensors and you name them "Cels" and "Cel2" my script will use them for single and dual battery monitoring.

To use the teensy to measure custom voltages would require both code changes on eric side and code changes on my side to expose the values unless eric's code sends the voltage as custom frsky sensors

Your options would be:
- regular FLVSS or VFAS frsky sensors (no code changes)
- custom teensy + custom yaapu script
- custom teensy

Alex

**Comment by yaapu** [comment]
If you check my latest beta [here](https://discuss.ardupilot.org/t/an-open-source-frsky-telemetry-script-for-the-horus-x10-x12-and-taranis-x9d-x9e-and-qx7-radios/26443/637) you'll find a version that
- supports PX4 flight modes
- supports custom frsky sensors
