### ISSUE TITLE
not all telemetry from Inav except GPS koordinates and a few other

### ISSUE THREAD

**Issue by Tekniqueman** [yaapu/FrskyTelemetryScript#60]
I love your GPS mapping you have done, but I don't understand why the other sensors is not accepted 
 from Inav. It just say no telemetry but some values is shown on the screen anyway. id it the names that's wrong or what can I do TO make it work like the map do?

**Comment by yaapu** [comment]
This widget does not work with iNav it's for Ardupilot only.
