### ISSUE TITLE
Feature request: acoustic variometer

### ISSUE THREAD

**Issue by blaab2** [yaapu/FrskyTelemetryScript#61]
Would be great if an acoustic variometer would be available. What do you think? Is this theoretically possible?

**Comment by yaapu** [comment]
it is already possible by using OpenTX built in variometer feature. 
In the telemetry page select VSpd as the vario source ad then enable vario sound like in this video https://www.youtube.com/watch?v=gN_5zIKE59s
( I tried it once a while ago and don't recall if the vario source is VSpd or Alt)
