### ISSUE TITLE
Vehicle 'boat' currently not supported?

### ISSUE THREAD

**Issue by WillyZehnder** [yaapu/FrskyTelemetryScript#62]
I’m using the script on a boat and I don’t have an info about actual flight mode on screen and no announcment-sound on mode-change.
All other things are working perfectly.

**Comment by yaapu** [comment]
Hi Willy please excuse me for such a late reply, which radio do you have so I can prepare a test version?

**Comment by WillyZehnder** [comment]
Hi Alex, in that weird times many things are more urgent than our hobbies.

I put on my thinking cap and changed my mind: I would prefer to test your script dirctly on my target system Taranis X9E (if you not yet started to prepare for QX7).

**Comment by yaapu** [comment]
fixed in 1.9.1
