### ISSUE TITLE
Custom Sensor Data?

### ISSUE THREAD

**Issue by FairweatherIT** [yaapu/FrskyTelemetryScript#64]
We have a lightware LW20 connected by serial (Telem 2 port) on one of out hex copters with a pixhawk 2.1 blue cube.  I can view the "Sonar Range" value in Mission Planner, can this value be relayed to the Horus so distance to ground can be viewed on the Horus screen?

**Comment by yaapu** [comment]
Hi, didi you make it work, looks like the most recent MavToPT code supports rangefinders just fine?

**Comment by FairweatherIT** [comment]
Greetings Alessandro...I have not tested again since yesterday. I will do so this afternoon and report back.  Thanks for your help yesterday.
