### ISSUE TITLE
Flight Mode Confliction with multiple MAV IDs

### ISSUE THREAD

**Issue by mike-bfd** [yaapu/FrskyTelemetryScript#67]
When attaching a Gremsy gimbal to the pixhawk via Mavlink, I noticed that the flight mode constantly changes. When this gimbal is connected to the aircraft, it appears as a second vehicle, with it's own data stream. (In mission planner, you can select the aircraft or the gimbal in the vehicle drop-down next to the connect button). I believe that the script is interpreting both vehicles somehow.

I have attached a video and tlog to hopefully help explain.
[https://drive.google.com/drive/folders/1ZPfU7rXaT2E5CgQCuOD5_RAK1FszSysk?usp=sharing](https://drive.google.com/drive/folders/1ZPfU7rXaT2E5CgQCuOD5_RAK1FszSysk?usp=sharing
)

The architecture:
Cube Orange FC:
Air Radio: RFD900ux
Ground Radio: RFD900 TX MOD - Wifi (udp) to Mission Planner.

**Comment by yaapu** [comment]
Hi, this is an issue with the MavToPT code on the TX MOD you better ask for help to Eric Stockenstrom here https://github.com/zs6buj/MavlinkToPassthru/issues

**Comment by mike-bfd** [comment]
Thanks! Closing here to re-open on Mav2PT

**Comment by yaapu** [comment]
Hi Mike, I kind of remember that Eric solved a similar issue with another device acting weird on the mavlink bus
