### ISSUE TITLE
Add direct link to proper GMAPcatcher exe

### ISSUE THREAD

**Issue by Hwurzburg** [yaapu/FrskyTelemetryScript#68]
Github sucks at intuitively showing how to download this....people will mistakenly download the wrong one....had to help Tridge find the right one...
just a link in the wiki to :https://github.com/yaapu/GMapCatcher/releases/download/yaapu-0.8.1.0/GMapCatcher-0.8.1.0.exe

also the video is misleading now on resizing tiles....if you like I will try to edit it to fix that...

**Comment by yaapu** [comment]
hi Henry, link fixed thanks, about the video I migh ask the author to fix it, or you can edit it but it's not mine

**Comment by yaapu** [comment]
updated the wiki page with your contribution
