### ISSUE TITLE
Upload waypoints to pixhawk?

### ISSUE THREAD

**Issue by wouterkattenbeld** [yaapu/FrskyTelemetryScript#69]
Hello,

I use a pixhawk on my baitboat.
I also use a Ground Control Center app on my android tablet to upload waypoints to the boat.
After i upload the waypoint, i use my Transmitter to put the boat in Auto mode.

Is it possible to upload a waypoint from the OpenTX transmitter to the pixhawk without use a Ground Control Center app?

**Comment by yaapu** [comment]
Hi, no it's not possible, waypoint support is not implemented
