### ISSUE TITLE
Add sound files for soaring status text messages 

### ISSUE THREAD

**Issue by yaapu** [yaapu/FrskyTelemetryScript#72]

**Comment by WillyZehnder** [comment]
...and for the new mode THERMAL.

The weather is becoming better these days and it would be very helpful to have that sound-announcements :o)

I would be happy to test that feature as beta on my Taranis X9E.

**Comment by yaapu** [comment]
@WillyZehnder this issue is closed on the dev branch, please try https://github.com/yaapu/FrskyTelemetryScript/releases/tag/Taranis-1.9.4_beta1

If you use this along latest master you'll have height above terrain support, please use the"min" version on hud and possibly right panel to save some memory if your x9d is non a 2019 model.

**Comment by yaapu** [comment]
version 1.9.5
