### ISSUE TITLE
X7 Access yaapu script says no telemetry when there is.

### ISSUE THREAD

**Issue by jimdgit** [yaapu/FrskyTelemetryScript#75]
open-tx 2.3.9 frsky - Yaapu X7 1.8.0
PIX4 v1.11.1
There is telemetry but the script says there is not.
That  message goes away but still does not display telemetry.
I can see the data on other screens I have set up.

**Comment by yaapu** [comment]
Hi no support for PX4, please check [this](https://discuss.px4.io/t/yaapu-lua-fully-functional-and-supported-with-px4-firmware/12708)
