### ISSUE TITLE
 The counter resets at 60:00?

### ISSUE THREAD

**Issue by Damian650** [yaapu/FrskyTelemetryScript#77]
Hello, please excuse me first, my English is poor, so I am using the translator.
 I was presented with the following problem:
       When I reset the counter, it always goes to 60:00, never 00:00.
       Has it happened to someone else?

My radio is a TX16S Radiomaster.

![IMG_20201105_234132](https://user-images.githubusercontent.com/74032357/98320181-2c75d100-1fc1-11eb-9eb7-b5ae7539c88c.jpg)

**Comment by yaapu** [comment]
Sorry for the late reply, I can't reproduce the issue, are you sure you do not have another script/function modifying timer 3 which is used for the flight timer?

**Comment by Damian650** [comment]
Hi.
Thank you for taking the time to respond.
Just before reading the answer, I decided to format the SD.
I was installing the scripts one by one, until one of them generated the error, the script is that of "iNav"
So I'm going to choose not to use it.

The Scripts I am using are the following:
[https://github.com/yaapu/FrskyTelemetryScript](url) 
[https://github.com/yaapu/HorusMappingWidget](url)

Y este es el que causaba el error:
[https://github.com/iNavFlight/LuaTelemetry](url)


I am going to reconfigure my radio and when I finish if the problem does not arise again I will give the issue as resolved.

Many thanks.

**Comment by yaapu** [comment]
I didn't know lua iNav manipulated timer 3, thanks for reporting back
