### ISSUE TITLE
Yaapu.lua and yaapu.luac are the same

### ISSUE THREAD

**Issue by Michael-Ringstrasse** [yaapu/FrskyTelemetryScript#79]
Hello together,

I am Michael and I am new on this board. 
And my English is bad,  sorry.

Yesterday I save the ZIP wird Yaapu Telemetri for my Taranis QX7. But today I Fund out, that the lua script does not work. When I checked the file yaapu7.lua I cannot read any Character because lua and luac are the same. 

Please change the file yaapu7.lua.

**Comment by yaapu** [comment]
Hi that's correct, they are both binary compiled and that's not the reason your setup is failing.

**Comment by Michael-Ringstrasse** [comment]
Hi, thank you for your answer. 
The setup ist running now. The could be found while I use wrong Folders on the SD card, but I am not shure.
