### ISSUE TITLE
Feature Request: SatCount sensor

### ISSUE THREAD

**Issue by RMFPV** [yaapu/FrskyTelemetryScript#8]
Can you please add SatCount sensor to be discovered?
Thank you.

**Comment by yaapu** [comment]
Hi, I recently removed it, used to be there, I'll add it back :)

**Comment by yaapu** [comment]
How about using HDOP instead of satcount wouldn't it provide a better indication of GPS lock quality?

**Comment by MFlghts** [comment]
I would like to use it for low sats alarm.
Thank you!

**Comment by yaapu** [comment]
What you are looking for is a way to have vocal alert whenever the hdop falls below some threshhold?

**Comment by yaapu** [comment]
Ardupilot has a default GPS_HDOP_GOOD of 2.0, I could report low gps hdop whenever it raises above 2 after having been lower

**Comment by yaapu** [comment]
having a dedicated menu entry for setting the threshold is IMO overkill and would "eat" some precious memory

**Comment by MFlghts** [comment]
My particular case is that sometimes GPS gets jammed in the area I'm flying. I was planing to make an audio alarm using special functions + logical switch to play SatsCount value when it drops to less than 4 sats. Your idea with HDOP is even better! I think any of them will do a job.
Just please make it constantly repeat the warning with 5 sec interval, or so.
Thank you!

**Comment by yaapu** [comment]
I'll think about it, ideally there should be a menu entry to enable the feature, then you could configure the periodic alert with the already existing entry. 
Vocal "low HDOP alert" would be nice :-)

btw: do  you get "GPS glitch" alerts on the message bar when GPS gets jammed?

**Comment by MFlghts** [comment]
I've just recently started using your brilliant script, I didn't check "GPS glitch" alert yet. Will do next time.
Before I just used OpenTx voice alert for low sats. OpenTx doesn't really natively support all this GPS stuff by default.

**Comment by MFlghts** [comment]
Hi yaapu!
I've just installed the last version but seems there is no SatCount sensor in it.
Can you be so kind to add it, as we discussed.

Concerning your question about "GPS glitch" alerts on the message bar when GPS gets jammed - can you please explain what do you mean by GPS gets jammed?
If GPS sats become 0 - voice Alert "GPS lost" is activated. Is there supposed to be some different scenario?

**Comment by yaapu** [comment]
Hi,
I did implement the high HDOP alert but was never able to trigger on the field.
I'll try to explain myself, with gps glitches I get "GPS Glitch" but hdop remains high, than "Glitch cleared" and the alert does not fire, if HDOP raises above minimum hdop configured in ardupilot I get an EKF variance error which eventually triggers an ekf failsafe that plays an alert every 10secs.. so I could not find a valid use case for your request.

**Comment by MFlghts** [comment]
I want to use SatCount separately to set custom alerts via Taranis voice alarm let's say for 6 sats, 3 sats and 0 sats. This would keep me completely informed about GPS conditions.
Does this sound reasonable?

I might be wrong but somehow I don't like Hdop as it's seems to me that it's easer and more straightforward to control sats amount.

**Comment by MFlghts** [comment]
Hi! Can you please inform about any feature for this discussion?

**Comment by yaapu** [comment]
Hi,
I will not include sat count sensor in the mainstream code but I can make a special version for you that you'll have to maintain

**Comment by MFlghts** [comment]
This is very kind of you! I greatly appreciate it. 
I also had another idea which you didn't reply here ttps://github.com/yaapu/FrskyTelemetryScript/issues/20  , and it's very much connected to this one. Would be very nice if you can also tell will it be also implemented, or denied.
Thank you!

**Comment by yaapu** [comment]
Hi,
sorry for a very late replay, install latest version and overwrite yaapu9.luac with this 
[yaapu9_nsats.zip](https://github.com/yaapu/FrskyTelemetryScript/files/3321742/yaapu9_nsats.zip)

Alex

**Comment by MFlghts** [comment]
Thank you very much indeed!
I will try asap.

**Comment by MFlghts** [comment]
I'm very sorry, can you please compile it to yaapu7?
