### ISSUE TITLE
Heartbeat decode

### ISSUE THREAD

**Issue by galdalali** [yaapu/FrskyTelemetryScript#81]
Hi all,

I'm having an issue with yappu in my system which decodes heartbeats from different components in the Mavlink network and  declares false alarms because of that (flight mode change, arm/disarm).
I'm attaching 2 images:
1. Description of the system architecture
2. Partial Mavlink inspector screen with several heartbeats

Is it possible to tell yappu script to decode by component id? Because it seems it decodes heartbeats from everyone.

I don't think it belong here but I'll give it a try.. Can I somehow separate the two serial's in the autopilot itself so the yappu will not get the Mavlink data from telem1 port?

Thanks, Gal

![1313](https://user-images.githubusercontent.com/8566487/103176072-9c912c80-4877-11eb-957c-8de63b528fd4.png)
![1212](https://user-images.githubusercontent.com/8566487/103176073-9dc25980-4877-11eb-917a-92a141a5f888.png)

**Comment by yaapu** [comment]
Hi wrong place for your issue :-)
I guess you're using the MavToPT firmware which is the one doing the decoding, my scripts simply relies on the frsky telemetry generated by that firmware
