### ISSUE TITLE
Yaapu displays 'ALR' when telemetry is received

### ISSUE THREAD

**Issue by paulr4** [yaapu/FrskyTelemetryScript#82]
I'm new to Yaapu but with the help of several tutorials have succeeded in getting it running on my Radiomaster TX16S, running OpenTX 2.3.10. I'm using the Horus version of Yaapu.

Yaapu is displaying its default screen, with 'disarmed' and 'no gps' flashing on the screen, but as soon as I turn on the receiver side (Pixhawk 2.4.8 running PX4, converter cable, FrSky RX6R), I hear a buzz and '02:ALR' appears at the bottom of the screen in red.

I know my telemetry data is getting through to the transmitter, because I can see it in the telemetry setup page of OpenTX, with 20 or so telemetry variables coming through live. None of these are displayed by Yaapu though. The 'ALR' warning only displays once, even if I power the model down and up again; it's as if it has crashed. Am I doing something wrong?

**Comment by yaapu** [comment]
My script does not support PX4, only ardupilot is supported. You can however use the MavToPT firmware to use my scripts inserting a mavlink converter between the FC and your RX,  a simple search finds this which is well documented https://discuss.px4.io/t/yaapu-lua-fully-functional-and-supported-with-px4-firmware/12708
