### ISSUE TITLE
Enhancement: Audio/vocal airspeed alert

### ISSUE THREAD

**Issue by cheintz** [yaapu/FrskyTelemetryScript#84]
For plane models especially, it would be useful to receive audio warnings about low (or high) airspeed in a manner similar to what is provided for altitude. More frequent alerts when at low speed and at low altitude would be useful to help avoid stalling while landing.

**Comment by yaapu** [comment]
Hi, you can add OpenTX alerts monitoring the GSpd sensor which when an airspeed sensor is present adn enabled reports airspeed and not groundspeed

**Comment by hyperion11** [comment]
👍 
also wish this feature :) Like battery alarm

**Comment by Nerenye** [comment]
@yaapu i can´t get the Airspeed into Ethos with passthrough telemetry on. is there a way to enable it anyway?

**Comment by yaapu** [comment]
this was addressed by "lua sources" in ethos
