### ISSUE TITLE
Support for OpenTX 2.1  (AVR based Radios)

### ISSUE THREAD

**Issue by UltraWhiteAngel** [yaapu/FrskyTelemetryScript#85]
I was wondering if this is attempted, or even possible to make it work on Mega2560 based radios.
#

**Comment by yaapu** [comment]
Hi, lua memory requirements are pretty high, on Taranis radios my script needs about 65K, on Horus around 200K, doubt it will ever fit on Mega2560...

**Comment by UltraWhiteAngel** [comment]
Thanks for the awesome Script, unfortunately I am building my first openTX radio, and wanted to experience the Frsky features to full.
I think it's better to wait for Jumper/RadioKing to release a new affordable radio to release.
