### ISSUE TITLE
(Minor) telemetry.gpsHdopC comment about it's unit

### ISSUE THREAD

**Issue by rotorman** [yaapu/FrskyTelemetryScript#87]
https://github.com/yaapu/FrskyTelemetryScript/blob/82b2245639e209b875b994cc9dd0ae2e9f4e3f0e/HORUS/SOURCES/SRC/WIDGETS/Yaapu/main.lua#L857

This value stems in Mav2PT from [MAVLink GPS_RAW_INT (#24)](https://mavlink.io/en/messages/common.html#GPS_RAW_INT) uint16_t field **eph**, which is GPS HDOP horizontal dilution of position (unitless).

Mav2PT does some conversion to it:
https://github.com/zs6buj/MavlinkToPassthru/blob/0f469ce22c8c3f8d7d224751a2ccf244df9069f8/MavToPass_v2.63.11/MavToPass_v2.63.11.ino#L1949
and
https://github.com/zs6buj/MavlinkToPassthru/blob/0f469ce22c8c3f8d7d224751a2ccf244df9069f8/MavToPass_v2.63.11/FrSky_Ports.h#L1792
and
https://github.com/zs6buj/MavlinkToPassthru/blob/0f469ce22c8c3f8d7d224751a2ccf244df9069f8/MavToPass_v2.63.11/FrSky_Ports.h#L1808
before sending it out:
https://github.com/zs6buj/MavlinkToPassthru/blob/0f469ce22c8c3f8d7d224751a2ccf244df9069f8/MavToPass_v2.63.11/FrSky_Ports.h#L1818

After division with 10 and splitting it to value and multiplier, it still is unitless, thus I guess the "dm" in comment is misleading.

**Comment by yaapu** [comment]
agree, no unit on diluition, thanks
