### ISSUE TITLE
(Minor) Comment of unit of dilution of precision. It should be unitless

### ISSUE THREAD

**Issue by rotorman** [yaapu/FrskyTelemetryScript#88]
Minor problem, but nevertheless it would be nice to have it correct - please check the comment on this line, "dm" seems wrong, as (horizontal) dilution of precision should be unitless:
https://github.com/yaapu/FrskyTelemetryScript/blob/82b2245639e209b875b994cc9dd0ae2e9f4e3f0e/HORUS/SOURCES/SRC/WIDGETS/Yaapu/main.lua#L857

**Comment by yaapu** [comment]
agree, no unit on diluition, thanks

**Comment by rotorman** [comment]
Fixed in a PR #90 that I created.
