### ISSUE TITLE
Feature Request: LiOn voltage alarm

### ISSUE THREAD

**Issue by MFlghts** [yaapu/FrskyTelemetryScript#9]
Please extend min voltage alarm option to 2.8V. 
Many people fly Lions which can be safely discharged to 2.5V.

**Comment by yaapu** [comment]
Hi will do, Horus version already has extended range for voltage alarm. Thanks

**Comment by MFlghts** [comment]
Thank you!

**Comment by yaapu** [comment]
Latest Taranis version has no restrictions on voltage alarms

**Comment by MFlghts** [comment]
Thank you!
