### ISSUE TITLE
Pre Processed folder?

### ISSUE THREAD

**Issue by radiohound** [yaapu/FrskyTelemetryScript#97]
On version 1.8.1 you have included a pre processed PP folder with the pre processed LUA's. Would that be possible to include in the latest version? 

like:
https://github.com/yaapu/FrskyTelemetryScript/tree/master/HORUS/SOURCES/PP

Thank you!

**Comment by 0815Creeper** [comment]
I would be happy if there where instructions on how to use the preprocessor... The compilation link in the github-wiki does not lead anywhere...

**Comment by radiohound** [comment]
Sorry, I somehow missed that they are located here FrskyTelemetryScript-Horus-Widget-1.9.3-beta4\HORUS\SOURCES\SRC
