### ISSUE TITLE
Wrong Flightmodes

### ISSUE THREAD

**Issue by Almischalmi** [yaapu/FrskyTelemetryScript#98]
Not sure if this is an issue with your widget or TXMOD, but using TXMOD I sometimes get the wrong Flightmodes in the Widget. Power cycling the radio usually helps.

Using latest Dev-Ardupilot and 1.9.3-beta.

![IMG_1992](https://user-images.githubusercontent.com/64095900/109292190-48300c00-782a-11eb-96a7-606063a94470.JPG)

**Comment by yaapu** [comment]
Hi, unfortunately flight modes are reported as sent by TXMOD so you should contact them for support!
