### ISSUE TITLE
Script Syntax Error - bad argument

### ISSUE THREAD

**Issue by PhilColbert** [yaapu/FrskyTelemetryScript#99]
In mission mode, as soon as a waypoint is reached, the script fails with

Script syntax error
bad argument #1 to 'match'( string expec

Image : http://airwhere.co.uk/downloads/yappu.jpg

Works perfectly otherwise....

Any ideas ?

Thanks

 1.9.1
Radio : Taranis
R9mm - smartport
Omnibus FC

**Comment by yaapu** [comment]
damn...I can reproduce this, thanks

**Comment by yaapu** [comment]
fixed https://github.com/yaapu/FrskyTelemetryScript/releases/tag/Taranis-1.9.1_beta2

**Comment by PhilColbert** [comment]
Thanks for all the work, awesome stuff ! :)
